// Generated from the captured KRIC route responses used by the line-sync audit.
// Keep this bundled snapshot so station selection also works when the API is unavailable.

import type { Station } from "./station.types";

export const stationCatalog: Station[] = [
  {
    id: "5:2511",
    stationKey: "5:2511",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2511",
    stationName: "방화",
    lineOrder: 1,
    journeySupported: true,
  },
  {
    id: "5:2512",
    stationKey: "5:2512",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2512",
    stationName: "개화산",
    lineOrder: 2,
    journeySupported: true,
  },
  {
    id: "5:2513",
    stationKey: "transfer:김포공항",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2513",
    stationName: "김포공항",
    lineOrder: 3,
    journeySupported: true,
  },
  {
    id: "5:2514",
    stationKey: "5:2514",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2514",
    stationName: "송정",
    lineOrder: 4,
    journeySupported: true,
  },
  {
    id: "5:2515",
    stationKey: "5:2515",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2515",
    stationName: "마곡",
    lineOrder: 5,
    journeySupported: true,
  },
  {
    id: "5:2516",
    stationKey: "5:2516",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2516",
    stationName: "발산",
    lineOrder: 6,
    journeySupported: true,
  },
  {
    id: "5:2517",
    stationKey: "5:2517",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2517",
    stationName: "우장산",
    lineOrder: 7,
    journeySupported: true,
  },
  {
    id: "5:2518",
    stationKey: "5:2518",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2518",
    stationName: "화곡",
    lineOrder: 8,
    journeySupported: true,
  },
  {
    id: "5:2519",
    stationKey: "transfer:까치산",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2519",
    stationName: "까치산",
    lineOrder: 9,
    journeySupported: true,
  },
  {
    id: "5:2520",
    stationKey: "5:2520",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2520",
    stationName: "신정(은행정)",
    lineOrder: 10,
    journeySupported: true,
  },
  {
    id: "5:2521",
    stationKey: "5:2521",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2521",
    stationName: "목동",
    lineOrder: 11,
    journeySupported: true,
  },
  {
    id: "5:2522",
    stationKey: "5:2522",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2522",
    stationName: "오목교(목동운동장앞)",
    lineOrder: 12,
    journeySupported: true,
  },
  {
    id: "5:2523",
    stationKey: "5:2523",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2523",
    stationName: "양평",
    lineOrder: 13,
    journeySupported: true,
  },
  {
    id: "5:2524",
    stationKey: "transfer:영등포구청",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2524",
    stationName: "영등포구청",
    lineOrder: 14,
    journeySupported: true,
  },
  {
    id: "5:2525",
    stationKey: "5:2525",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2525",
    stationName: "영등포시장",
    lineOrder: 15,
    journeySupported: true,
  },
  {
    id: "5:2526",
    stationKey: "transfer:신길",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2526",
    stationName: "신길",
    lineOrder: 16,
    journeySupported: true,
  },
  {
    id: "5:2527",
    stationKey: "5:2527",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2527",
    stationName: "여의도",
    lineOrder: 17,
    journeySupported: true,
  },
  {
    id: "5:2528",
    stationKey: "5:2528",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2528",
    stationName: "여의나루",
    lineOrder: 18,
    journeySupported: true,
  },
  {
    id: "5:2529",
    stationKey: "5:2529",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2529",
    stationName: "마포",
    lineOrder: 19,
    journeySupported: true,
  },
  {
    id: "5:2530",
    stationKey: "transfer:공덕",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2530",
    stationName: "공덕",
    lineOrder: 20,
    journeySupported: true,
  },
  {
    id: "5:2531",
    stationKey: "5:2531",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2531",
    stationName: "애오개",
    lineOrder: 21,
    journeySupported: true,
  },
  {
    id: "5:2532",
    stationKey: "transfer:충정로",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2532",
    stationName: "충정로(경기대입구)",
    lineOrder: 22,
    journeySupported: true,
  },
  {
    id: "5:2533",
    stationKey: "5:2533",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2533",
    stationName: "서대문",
    lineOrder: 23,
    journeySupported: true,
  },
  {
    id: "5:2534",
    stationKey: "5:2534",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2534",
    stationName: "광화문(세종문화회관)",
    lineOrder: 24,
    journeySupported: true,
  },
  {
    id: "5:2535",
    stationKey: "transfer:종로3가",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2535",
    stationName: "종로3가(탑골공원)",
    lineOrder: 25,
    journeySupported: true,
  },
  {
    id: "5:2536",
    stationKey: "transfer:을지로4가",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2536",
    stationName: "을지로4가",
    lineOrder: 26,
    journeySupported: true,
  },
  {
    id: "5:2537",
    stationKey: "transfer:동대문역사문화공원",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2537",
    stationName: "동대문역사문화공원",
    lineOrder: 27,
    journeySupported: true,
  },
  {
    id: "5:2538",
    stationKey: "5:2538",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2538",
    stationName: "청구",
    lineOrder: 28,
    journeySupported: true,
  },
  {
    id: "5:2539",
    stationKey: "5:2539",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2539",
    stationName: "신금호",
    lineOrder: 29,
    journeySupported: true,
  },
  {
    id: "5:2540",
    stationKey: "5:2540",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2540",
    stationName: "행당",
    lineOrder: 30,
    journeySupported: true,
  },
  {
    id: "5:2541",
    stationKey: "transfer:왕십리",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2541",
    stationName: "왕십리",
    lineOrder: 31,
    journeySupported: true,
  },
  {
    id: "5:2542",
    stationKey: "5:2542",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2542",
    stationName: "마장",
    lineOrder: 32,
    journeySupported: true,
  },
  {
    id: "5:2543",
    stationKey: "5:2543",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2543",
    stationName: "답십리",
    lineOrder: 33,
    journeySupported: true,
  },
  {
    id: "5:2544",
    stationKey: "5:2544",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2544",
    stationName: "장한평",
    lineOrder: 34,
    journeySupported: true,
  },
  {
    id: "5:2545",
    stationKey: "5:2545",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2545",
    stationName: "군자(능동)",
    lineOrder: 35,
    journeySupported: true,
  },
  {
    id: "5:2546",
    stationKey: "5:2546",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2546",
    stationName: "아차산(어린이대공원후문)",
    lineOrder: 36,
    journeySupported: true,
  },
  {
    id: "5:2547",
    stationKey: "5:2547",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2547",
    stationName: "광나루(장신대)",
    lineOrder: 37,
    journeySupported: true,
  },
  {
    id: "5:2548",
    stationKey: "5:2548",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2548",
    stationName: "천호(풍납토성)",
    lineOrder: 38,
    journeySupported: true,
  },
  {
    id: "5:2549",
    stationKey: "5:2549",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2549",
    stationName: "강동",
    lineOrder: 39,
    journeySupported: true,
  },
  {
    id: "5:2550",
    stationKey: "5:2550",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2550",
    stationName: "길동",
    lineOrder: 40,
    journeySupported: true,
  },
  {
    id: "5:2555",
    stationKey: "5:2555",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2555",
    stationName: "둔촌동",
    lineOrder: 40,
    journeySupported: true,
  },
  {
    id: "5:2551",
    stationKey: "5:2551",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2551",
    stationName: "굽은다리(강동구민회관앞)",
    lineOrder: 41,
    journeySupported: true,
  },
  {
    id: "5:2556",
    stationKey: "5:2556",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2556",
    stationName: "올림픽공원(한국체대)",
    lineOrder: 41,
    journeySupported: true,
  },
  {
    id: "5:2557",
    stationKey: "5:2557",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2557",
    stationName: "방이",
    lineOrder: 42,
    journeySupported: true,
  },
  {
    id: "5:2552",
    stationKey: "5:2552",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2552",
    stationName: "명일",
    lineOrder: 42,
    journeySupported: true,
  },
  {
    id: "5:2558",
    stationKey: "transfer:오금",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2558",
    stationName: "오금",
    lineOrder: 43,
    journeySupported: true,
  },
  {
    id: "5:2553",
    stationKey: "5:2553",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2553",
    stationName: "고덕",
    lineOrder: 43,
    journeySupported: true,
  },
  {
    id: "5:2559",
    stationKey: "5:2559",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2559",
    stationName: "개롱",
    lineOrder: 44,
    journeySupported: true,
  },
  {
    id: "5:2554",
    stationKey: "5:2554",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2554",
    stationName: "상일동",
    lineOrder: 44,
    journeySupported: true,
  },
  {
    id: "5:2562",
    stationKey: "5:2562",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2562",
    stationName: "강일",
    lineOrder: 45,
    journeySupported: true,
  },
  {
    id: "5:2560",
    stationKey: "5:2560",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2560",
    stationName: "거여",
    lineOrder: 45,
    journeySupported: true,
  },
  {
    id: "5:2561",
    stationKey: "5:2561",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2561",
    stationName: "마천",
    lineOrder: 46,
    journeySupported: true,
  },
  {
    id: "5:2563",
    stationKey: "5:2563",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2563",
    stationName: "미사",
    lineOrder: 46,
    journeySupported: true,
  },
  {
    id: "5:2564",
    stationKey: "5:2564",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2564",
    stationName: "하남풍산",
    lineOrder: 47,
    journeySupported: true,
  },
  {
    id: "5:2565",
    stationKey: "5:2565",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2565",
    stationName: "하남시청(덕풍.신장)",
    lineOrder: 49,
    journeySupported: true,
  },
  {
    id: "5:2566",
    stationKey: "5:2566",
    lineId: "5",
    lineName: "5호선",
    stationCode: "2566",
    stationName: "하남검단산역",
    lineOrder: 50,
    journeySupported: true,
  },
  {
    id: "1:100-3",
    stationKey: "1:100-3",
    lineId: "1",
    lineName: "1호선",
    stationCode: "100-3",
    stationName: "연천",
    lineOrder: 1,
    journeySupported: false,
  },
  {
    id: "1:100-2",
    stationKey: "1:100-2",
    lineId: "1",
    lineName: "1호선",
    stationCode: "100-2",
    stationName: "전곡",
    lineOrder: 2,
    journeySupported: false,
  },
  {
    id: "1:100-1",
    stationKey: "1:100-1",
    lineId: "1",
    lineName: "1호선",
    stationCode: "100-1",
    stationName: "청산",
    lineOrder: 3,
    journeySupported: false,
  },
  {
    id: "1:100",
    stationKey: "1:100",
    lineId: "1",
    lineName: "1호선",
    stationCode: "100",
    stationName: "소요산",
    lineOrder: 4,
    journeySupported: false,
  },
  {
    id: "1:101",
    stationKey: "1:101",
    lineId: "1",
    lineName: "1호선",
    stationCode: "101",
    stationName: "동두천",
    lineOrder: 5,
    journeySupported: false,
  },
  {
    id: "1:102",
    stationKey: "1:102",
    lineId: "1",
    lineName: "1호선",
    stationCode: "102",
    stationName: "보산",
    lineOrder: 6,
    journeySupported: false,
  },
  {
    id: "1:103",
    stationKey: "1:103",
    lineId: "1",
    lineName: "1호선",
    stationCode: "103",
    stationName: "동두천중앙",
    lineOrder: 7,
    journeySupported: false,
  },
  {
    id: "1:104",
    stationKey: "1:104",
    lineId: "1",
    lineName: "1호선",
    stationCode: "104",
    stationName: "지행",
    lineOrder: 8,
    journeySupported: false,
  },
  {
    id: "1:105",
    stationKey: "1:105",
    lineId: "1",
    lineName: "1호선",
    stationCode: "105",
    stationName: "덕정",
    lineOrder: 9,
    journeySupported: false,
  },
  {
    id: "1:106",
    stationKey: "1:106",
    lineId: "1",
    lineName: "1호선",
    stationCode: "106",
    stationName: "덕계",
    lineOrder: 10,
    journeySupported: false,
  },
  {
    id: "1:107",
    stationKey: "1:107",
    lineId: "1",
    lineName: "1호선",
    stationCode: "107",
    stationName: "양주",
    lineOrder: 11,
    journeySupported: false,
  },
  {
    id: "1:108",
    stationKey: "1:108",
    lineId: "1",
    lineName: "1호선",
    stationCode: "108",
    stationName: "녹양",
    lineOrder: 12,
    journeySupported: false,
  },
  {
    id: "1:109",
    stationKey: "1:109",
    lineId: "1",
    lineName: "1호선",
    stationCode: "109",
    stationName: "가능",
    lineOrder: 13,
    journeySupported: false,
  },
  {
    id: "1:110",
    stationKey: "1:110",
    lineId: "1",
    lineName: "1호선",
    stationCode: "110",
    stationName: "의정부",
    lineOrder: 14,
    journeySupported: false,
  },
  {
    id: "1:111",
    stationKey: "1:111",
    lineId: "1",
    lineName: "1호선",
    stationCode: "111",
    stationName: "회룡",
    lineOrder: 15,
    journeySupported: false,
  },
  {
    id: "1:112",
    stationKey: "1:112",
    lineId: "1",
    lineName: "1호선",
    stationCode: "112",
    stationName: "망월사",
    lineOrder: 16,
    journeySupported: false,
  },
  {
    id: "1:113",
    stationKey: "1:113",
    lineId: "1",
    lineName: "1호선",
    stationCode: "113",
    stationName: "도봉산",
    lineOrder: 17,
    journeySupported: false,
  },
  {
    id: "1:114",
    stationKey: "1:114",
    lineId: "1",
    lineName: "1호선",
    stationCode: "114",
    stationName: "도봉",
    lineOrder: 18,
    journeySupported: false,
  },
  {
    id: "1:115",
    stationKey: "1:115",
    lineId: "1",
    lineName: "1호선",
    stationCode: "115",
    stationName: "방학",
    lineOrder: 19,
    journeySupported: false,
  },
  {
    id: "1:116",
    stationKey: "1:116",
    lineId: "1",
    lineName: "1호선",
    stationCode: "116",
    stationName: "창동",
    lineOrder: 20,
    journeySupported: false,
  },
  {
    id: "1:117",
    stationKey: "1:117",
    lineId: "1",
    lineName: "1호선",
    stationCode: "117",
    stationName: "녹천",
    lineOrder: 21,
    journeySupported: false,
  },
  {
    id: "1:118",
    stationKey: "1:118",
    lineId: "1",
    lineName: "1호선",
    stationCode: "118",
    stationName: "월계",
    lineOrder: 22,
    journeySupported: false,
  },
  {
    id: "1:119",
    stationKey: "1:119",
    lineId: "1",
    lineName: "1호선",
    stationCode: "119",
    stationName: "광운대",
    lineOrder: 23,
    journeySupported: false,
  },
  {
    id: "1:120",
    stationKey: "1:120",
    lineId: "1",
    lineName: "1호선",
    stationCode: "120",
    stationName: "석계",
    lineOrder: 24,
    journeySupported: false,
  },
  {
    id: "1:121",
    stationKey: "1:121",
    lineId: "1",
    lineName: "1호선",
    stationCode: "121",
    stationName: "신이문",
    lineOrder: 25,
    journeySupported: false,
  },
  {
    id: "1:122",
    stationKey: "1:122",
    lineId: "1",
    lineName: "1호선",
    stationCode: "122",
    stationName: "외대앞",
    lineOrder: 26,
    journeySupported: false,
  },
  {
    id: "1:123",
    stationKey: "transfer:회기",
    lineId: "1",
    lineName: "1호선",
    stationCode: "123",
    stationName: "회기",
    lineOrder: 27,
    journeySupported: false,
  },
  {
    id: "1:158",
    stationKey: "transfer:청량리",
    lineId: "1",
    lineName: "1호선",
    stationCode: "158",
    stationName: "청량리(서울시립대입구)",
    lineOrder: 28,
    journeySupported: false,
  },
  {
    id: "1:157",
    stationKey: "1:157",
    lineId: "1",
    lineName: "1호선",
    stationCode: "157",
    stationName: "제기동",
    lineOrder: 29,
    journeySupported: false,
  },
  {
    id: "1:156",
    stationKey: "transfer:신설동",
    lineId: "1",
    lineName: "1호선",
    stationCode: "156",
    stationName: "신설동",
    lineOrder: 30,
    journeySupported: false,
  },
  {
    id: "1:159",
    stationKey: "1:159",
    lineId: "1",
    lineName: "1호선",
    stationCode: "159",
    stationName: "동묘앞",
    lineOrder: 31,
    journeySupported: false,
  },
  {
    id: "1:155",
    stationKey: "1:155",
    lineId: "1",
    lineName: "1호선",
    stationCode: "155",
    stationName: "동대문",
    lineOrder: 32,
    journeySupported: false,
  },
  {
    id: "1:154",
    stationKey: "1:154",
    lineId: "1",
    lineName: "1호선",
    stationCode: "154",
    stationName: "종로5가",
    lineOrder: 33,
    journeySupported: false,
  },
  {
    id: "1:153",
    stationKey: "transfer:종로3가",
    lineId: "1",
    lineName: "1호선",
    stationCode: "153",
    stationName: "종로3가",
    lineOrder: 34,
    journeySupported: false,
  },
  {
    id: "1:152",
    stationKey: "1:152",
    lineId: "1",
    lineName: "1호선",
    stationCode: "152",
    stationName: "종각",
    lineOrder: 35,
    journeySupported: false,
  },
  {
    id: "1:151",
    stationKey: "transfer:시청",
    lineId: "1",
    lineName: "1호선",
    stationCode: "151",
    stationName: "시청",
    lineOrder: 36,
    journeySupported: false,
  },
  {
    id: "1:150",
    stationKey: "transfer:서울",
    lineId: "1",
    lineName: "1호선",
    stationCode: "150",
    stationName: "서울역",
    lineOrder: 37,
    journeySupported: false,
  },
  {
    id: "1:134",
    stationKey: "1:134",
    lineId: "1",
    lineName: "1호선",
    stationCode: "134",
    stationName: "남영",
    lineOrder: 38,
    journeySupported: false,
  },
  {
    id: "1:135",
    stationKey: "transfer:용산",
    lineId: "1",
    lineName: "1호선",
    stationCode: "135",
    stationName: "용산",
    lineOrder: 39,
    journeySupported: false,
  },
  {
    id: "1:136",
    stationKey: "1:136",
    lineId: "1",
    lineName: "1호선",
    stationCode: "136",
    stationName: "노량진",
    lineOrder: 40,
    journeySupported: false,
  },
  {
    id: "1:137",
    stationKey: "1:137",
    lineId: "1",
    lineName: "1호선",
    stationCode: "137",
    stationName: "대방",
    lineOrder: 41,
    journeySupported: false,
  },
  {
    id: "1:138",
    stationKey: "transfer:신길",
    lineId: "1",
    lineName: "1호선",
    stationCode: "138",
    stationName: "신길",
    lineOrder: 42,
    journeySupported: false,
  },
  {
    id: "1:139",
    stationKey: "1:139",
    lineId: "1",
    lineName: "1호선",
    stationCode: "139",
    stationName: "영등포",
    lineOrder: 43,
    journeySupported: false,
  },
  {
    id: "1:140",
    stationKey: "transfer:신도림",
    lineId: "1",
    lineName: "1호선",
    stationCode: "140",
    stationName: "신도림",
    lineOrder: 44,
    journeySupported: false,
  },
  {
    id: "1:141",
    stationKey: "1:141",
    lineId: "1",
    lineName: "1호선",
    stationCode: "141",
    stationName: "구로",
    lineOrder: 45,
    journeySupported: false,
  },
  {
    id: "1:142",
    stationKey: "1:142",
    lineId: "1",
    lineName: "1호선",
    stationCode: "142",
    stationName: "구일",
    lineOrder: 46,
    journeySupported: false,
  },
  {
    id: "1:P142",
    stationKey: "1:P142",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P142",
    stationName: "가산디지털단지",
    lineOrder: 46,
    journeySupported: false,
  },
  {
    id: "1:143",
    stationKey: "1:143",
    lineId: "1",
    lineName: "1호선",
    stationCode: "143",
    stationName: "개봉",
    lineOrder: 47,
    journeySupported: false,
  },
  {
    id: "1:P143",
    stationKey: "1:P143",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P143",
    stationName: "독산",
    lineOrder: 47,
    journeySupported: false,
  },
  {
    id: "1:P144",
    stationKey: "1:P144",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P144",
    stationName: "금천구청",
    lineOrder: 48,
    journeySupported: false,
  },
  {
    id: "1:144",
    stationKey: "1:144",
    lineId: "1",
    lineName: "1호선",
    stationCode: "144",
    stationName: "오류동",
    lineOrder: 48,
    journeySupported: false,
  },
  {
    id: "1:145",
    stationKey: "1:145",
    lineId: "1",
    lineName: "1호선",
    stationCode: "145",
    stationName: "온수",
    lineOrder: 49,
    journeySupported: false,
  },
  {
    id: "1:P144-1",
    stationKey: "1:P144-1",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P144-1",
    stationName: "광명",
    lineOrder: 49,
    journeySupported: false,
  },
  {
    id: "1:P145",
    stationKey: "1:P145",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P145",
    stationName: "석수",
    lineOrder: 49,
    journeySupported: false,
  },
  {
    id: "1:146",
    stationKey: "1:146",
    lineId: "1",
    lineName: "1호선",
    stationCode: "146",
    stationName: "역곡",
    lineOrder: 50,
    journeySupported: false,
  },
  {
    id: "1:P146",
    stationKey: "1:P146",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P146",
    stationName: "관악",
    lineOrder: 50,
    journeySupported: false,
  },
  {
    id: "1:147",
    stationKey: "1:147",
    lineId: "1",
    lineName: "1호선",
    stationCode: "147",
    stationName: "소사",
    lineOrder: 51,
    journeySupported: false,
  },
  {
    id: "1:P147",
    stationKey: "1:P147",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P147",
    stationName: "안양",
    lineOrder: 51,
    journeySupported: false,
  },
  {
    id: "1:148",
    stationKey: "1:148",
    lineId: "1",
    lineName: "1호선",
    stationCode: "148",
    stationName: "부천",
    lineOrder: 52,
    journeySupported: false,
  },
  {
    id: "1:P148",
    stationKey: "1:P148",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P148",
    stationName: "명학",
    lineOrder: 52,
    journeySupported: false,
  },
  {
    id: "1:P149",
    stationKey: "1:P149",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P149",
    stationName: "금정",
    lineOrder: 53,
    journeySupported: false,
  },
  {
    id: "1:149",
    stationKey: "1:149",
    lineId: "1",
    lineName: "1호선",
    stationCode: "149",
    stationName: "중동",
    lineOrder: 53,
    journeySupported: false,
  },
  {
    id: "1:P150",
    stationKey: "1:P150",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P150",
    stationName: "군포",
    lineOrder: 54,
    journeySupported: false,
  },
  {
    id: "1:150",
    stationKey: "1:150",
    lineId: "1",
    lineName: "1호선",
    stationCode: "150",
    stationName: "송내",
    lineOrder: 54,
    journeySupported: false,
  },
  {
    id: "1:151",
    stationKey: "1:151",
    lineId: "1",
    lineName: "1호선",
    stationCode: "151",
    stationName: "부개",
    lineOrder: 55,
    journeySupported: false,
  },
  {
    id: "1:P151",
    stationKey: "1:P151",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P151",
    stationName: "당정",
    lineOrder: 55,
    journeySupported: false,
  },
  {
    id: "1:P152",
    stationKey: "1:P152",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P152",
    stationName: "의왕",
    lineOrder: 56,
    journeySupported: false,
  },
  {
    id: "1:152",
    stationKey: "1:152",
    lineId: "1",
    lineName: "1호선",
    stationCode: "152",
    stationName: "부평",
    lineOrder: 56,
    journeySupported: false,
  },
  {
    id: "1:P153",
    stationKey: "1:P153",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P153",
    stationName: "성균관대",
    lineOrder: 57,
    journeySupported: false,
  },
  {
    id: "1:153",
    stationKey: "1:153",
    lineId: "1",
    lineName: "1호선",
    stationCode: "153",
    stationName: "백운",
    lineOrder: 57,
    journeySupported: false,
  },
  {
    id: "1:P154",
    stationKey: "1:P154",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P154",
    stationName: "화서",
    lineOrder: 58,
    journeySupported: false,
  },
  {
    id: "1:154",
    stationKey: "1:154",
    lineId: "1",
    lineName: "1호선",
    stationCode: "154",
    stationName: "동암",
    lineOrder: 58,
    journeySupported: false,
  },
  {
    id: "1:155",
    stationKey: "1:155",
    lineId: "1",
    lineName: "1호선",
    stationCode: "155",
    stationName: "간석",
    lineOrder: 59,
    journeySupported: false,
  },
  {
    id: "1:P155",
    stationKey: "1:P155",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P155",
    stationName: "수원",
    lineOrder: 59,
    journeySupported: false,
  },
  {
    id: "1:P156",
    stationKey: "1:P156",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P156",
    stationName: "세류",
    lineOrder: 60,
    journeySupported: false,
  },
  {
    id: "1:156",
    stationKey: "1:156",
    lineId: "1",
    lineName: "1호선",
    stationCode: "156",
    stationName: "주안",
    lineOrder: 60,
    journeySupported: false,
  },
  {
    id: "1:P157",
    stationKey: "1:P157",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P157",
    stationName: "병점",
    lineOrder: 61,
    journeySupported: false,
  },
  {
    id: "1:157",
    stationKey: "1:157",
    lineId: "1",
    lineName: "1호선",
    stationCode: "157",
    stationName: "도화",
    lineOrder: 61,
    journeySupported: false,
  },
  {
    id: "1:158",
    stationKey: "1:158",
    lineId: "1",
    lineName: "1호선",
    stationCode: "158",
    stationName: "제물포",
    lineOrder: 62,
    journeySupported: false,
  },
  {
    id: "1:P158",
    stationKey: "1:P158",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P158",
    stationName: "세마",
    lineOrder: 62,
    journeySupported: false,
  },
  {
    id: "1:P157-1",
    stationKey: "1:P157-1",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P157-1",
    stationName: "서동탄",
    lineOrder: 62,
    journeySupported: false,
  },
  {
    id: "1:159",
    stationKey: "1:159",
    lineId: "1",
    lineName: "1호선",
    stationCode: "159",
    stationName: "도원",
    lineOrder: 63,
    journeySupported: false,
  },
  {
    id: "1:P159",
    stationKey: "1:P159",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P159",
    stationName: "오산대",
    lineOrder: 63,
    journeySupported: false,
  },
  {
    id: "1:P160",
    stationKey: "1:P160",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P160",
    stationName: "오산",
    lineOrder: 64,
    journeySupported: false,
  },
  {
    id: "1:160",
    stationKey: "1:160",
    lineId: "1",
    lineName: "1호선",
    stationCode: "160",
    stationName: "동인천",
    lineOrder: 64,
    journeySupported: false,
  },
  {
    id: "1:161",
    stationKey: "1:161",
    lineId: "1",
    lineName: "1호선",
    stationCode: "161",
    stationName: "인천",
    lineOrder: 65,
    journeySupported: false,
  },
  {
    id: "1:P161",
    stationKey: "1:P161",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P161",
    stationName: "진위",
    lineOrder: 65,
    journeySupported: false,
  },
  {
    id: "1:P162",
    stationKey: "1:P162",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P162",
    stationName: "송탄",
    lineOrder: 66,
    journeySupported: false,
  },
  {
    id: "1:P163",
    stationKey: "1:P163",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P163",
    stationName: "서정리",
    lineOrder: 67,
    journeySupported: false,
  },
  {
    id: "1:P164",
    stationKey: "1:P164",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P164",
    stationName: "평택지제",
    lineOrder: 68,
    journeySupported: false,
  },
  {
    id: "1:P165",
    stationKey: "1:P165",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P165",
    stationName: "평택",
    lineOrder: 69,
    journeySupported: false,
  },
  {
    id: "1:P166",
    stationKey: "1:P166",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P166",
    stationName: "성환",
    lineOrder: 70,
    journeySupported: false,
  },
  {
    id: "1:P167",
    stationKey: "1:P167",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P167",
    stationName: "직산",
    lineOrder: 71,
    journeySupported: false,
  },
  {
    id: "1:P168",
    stationKey: "1:P168",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P168",
    stationName: "두정",
    lineOrder: 72,
    journeySupported: false,
  },
  {
    id: "1:P169",
    stationKey: "1:P169",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P169",
    stationName: "천안",
    lineOrder: 73,
    journeySupported: false,
  },
  {
    id: "1:P170",
    stationKey: "1:P170",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P170",
    stationName: "봉명",
    lineOrder: 74,
    journeySupported: false,
  },
  {
    id: "1:P171",
    stationKey: "1:P171",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P171",
    stationName: "쌍용(나사렛대)",
    lineOrder: 75,
    journeySupported: false,
  },
  {
    id: "1:P172",
    stationKey: "1:P172",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P172",
    stationName: "아산",
    lineOrder: 76,
    journeySupported: false,
  },
  {
    id: "1:P173",
    stationKey: "1:P173",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P173",
    stationName: "탕정",
    lineOrder: 77,
    journeySupported: false,
  },
  {
    id: "1:P174",
    stationKey: "1:P174",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P174",
    stationName: "배방",
    lineOrder: 78,
    journeySupported: false,
  },
  {
    id: "1:P176",
    stationKey: "1:P176",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P176",
    stationName: "온양온천",
    lineOrder: 79,
    journeySupported: false,
  },
  {
    id: "1:P177",
    stationKey: "1:P177",
    lineId: "1",
    lineName: "1호선",
    stationCode: "P177",
    stationName: "신창(순천향대)",
    lineOrder: 80,
    journeySupported: false,
  },
  {
    id: "2:201",
    stationKey: "transfer:시청",
    lineId: "2",
    lineName: "2호선",
    stationCode: "201",
    stationName: "시청",
    lineOrder: 1,
    journeySupported: false,
  },
  {
    id: "2:243",
    stationKey: "transfer:충정로",
    lineId: "2",
    lineName: "2호선",
    stationCode: "243",
    stationName: "충정로(경기대입구)",
    lineOrder: 2,
    journeySupported: false,
  },
  {
    id: "2:242",
    stationKey: "2:242",
    lineId: "2",
    lineName: "2호선",
    stationCode: "242",
    stationName: "아현",
    lineOrder: 3,
    journeySupported: false,
  },
  {
    id: "2:241",
    stationKey: "2:241",
    lineId: "2",
    lineName: "2호선",
    stationCode: "241",
    stationName: "이대",
    lineOrder: 4,
    journeySupported: false,
  },
  {
    id: "2:240",
    stationKey: "2:240",
    lineId: "2",
    lineName: "2호선",
    stationCode: "240",
    stationName: "신촌",
    lineOrder: 5,
    journeySupported: false,
  },
  {
    id: "2:239",
    stationKey: "transfer:홍대입구",
    lineId: "2",
    lineName: "2호선",
    stationCode: "239",
    stationName: "홍대입구",
    lineOrder: 6,
    journeySupported: false,
  },
  {
    id: "2:238",
    stationKey: "2:238",
    lineId: "2",
    lineName: "2호선",
    stationCode: "238",
    stationName: "합정",
    lineOrder: 7,
    journeySupported: false,
  },
  {
    id: "2:237",
    stationKey: "2:237",
    lineId: "2",
    lineName: "2호선",
    stationCode: "237",
    stationName: "당산",
    lineOrder: 8,
    journeySupported: false,
  },
  {
    id: "2:236",
    stationKey: "transfer:영등포구청",
    lineId: "2",
    lineName: "2호선",
    stationCode: "236",
    stationName: "영등포구청",
    lineOrder: 9,
    journeySupported: false,
  },
  {
    id: "2:235",
    stationKey: "2:235",
    lineId: "2",
    lineName: "2호선",
    stationCode: "235",
    stationName: "문래",
    lineOrder: 10,
    journeySupported: false,
  },
  {
    id: "2:234",
    stationKey: "transfer:신도림",
    lineId: "2",
    lineName: "2호선",
    stationCode: "234",
    stationName: "신도림",
    lineOrder: 11,
    journeySupported: false,
  },
  {
    id: "2:233",
    stationKey: "2:233",
    lineId: "2",
    lineName: "2호선",
    stationCode: "233",
    stationName: "대림(구로구청)",
    lineOrder: 12,
    journeySupported: false,
  },
  {
    id: "2:247",
    stationKey: "2:247",
    lineId: "2",
    lineName: "2호선",
    stationCode: "247",
    stationName: "도림천",
    lineOrder: 12,
    journeySupported: false,
  },
  {
    id: "2:248",
    stationKey: "2:248",
    lineId: "2",
    lineName: "2호선",
    stationCode: "248",
    stationName: "양천구청",
    lineOrder: 13,
    journeySupported: false,
  },
  {
    id: "2:232",
    stationKey: "2:232",
    lineId: "2",
    lineName: "2호선",
    stationCode: "232",
    stationName: "구로디지털단지",
    lineOrder: 13,
    journeySupported: false,
  },
  {
    id: "2:231",
    stationKey: "2:231",
    lineId: "2",
    lineName: "2호선",
    stationCode: "231",
    stationName: "신대방",
    lineOrder: 14,
    journeySupported: false,
  },
  {
    id: "2:249",
    stationKey: "2:249",
    lineId: "2",
    lineName: "2호선",
    stationCode: "249",
    stationName: "신정네거리",
    lineOrder: 14,
    journeySupported: false,
  },
  {
    id: "2:230",
    stationKey: "2:230",
    lineId: "2",
    lineName: "2호선",
    stationCode: "230",
    stationName: "신림",
    lineOrder: 15,
    journeySupported: false,
  },
  {
    id: "2:234-4",
    stationKey: "transfer:까치산",
    lineId: "2",
    lineName: "2호선",
    stationCode: "234-4",
    stationName: "까치산",
    lineOrder: 15,
    journeySupported: false,
  },
  {
    id: "2:229",
    stationKey: "2:229",
    lineId: "2",
    lineName: "2호선",
    stationCode: "229",
    stationName: "봉천",
    lineOrder: 16,
    journeySupported: false,
  },
  {
    id: "2:228",
    stationKey: "2:228",
    lineId: "2",
    lineName: "2호선",
    stationCode: "228",
    stationName: "서울대입구(관악구청)",
    lineOrder: 17,
    journeySupported: false,
  },
  {
    id: "2:227",
    stationKey: "2:227",
    lineId: "2",
    lineName: "2호선",
    stationCode: "227",
    stationName: "낙성대",
    lineOrder: 18,
    journeySupported: false,
  },
  {
    id: "2:226",
    stationKey: "2:226",
    lineId: "2",
    lineName: "2호선",
    stationCode: "226",
    stationName: "사당",
    lineOrder: 19,
    journeySupported: false,
  },
  {
    id: "2:225",
    stationKey: "2:225",
    lineId: "2",
    lineName: "2호선",
    stationCode: "225",
    stationName: "방배",
    lineOrder: 20,
    journeySupported: false,
  },
  {
    id: "2:224",
    stationKey: "2:224",
    lineId: "2",
    lineName: "2호선",
    stationCode: "224",
    stationName: "서초",
    lineOrder: 21,
    journeySupported: false,
  },
  {
    id: "2:223",
    stationKey: "transfer:교대",
    lineId: "2",
    lineName: "2호선",
    stationCode: "223",
    stationName: "교대(법원.검찰청)",
    lineOrder: 22,
    journeySupported: false,
  },
  {
    id: "2:222",
    stationKey: "2:222",
    lineId: "2",
    lineName: "2호선",
    stationCode: "222",
    stationName: "강남",
    lineOrder: 23,
    journeySupported: false,
  },
  {
    id: "2:221",
    stationKey: "2:221",
    lineId: "2",
    lineName: "2호선",
    stationCode: "221",
    stationName: "역삼",
    lineOrder: 24,
    journeySupported: false,
  },
  {
    id: "2:220",
    stationKey: "2:220",
    lineId: "2",
    lineName: "2호선",
    stationCode: "220",
    stationName: "선릉",
    lineOrder: 25,
    journeySupported: false,
  },
  {
    id: "2:219",
    stationKey: "2:219",
    lineId: "2",
    lineName: "2호선",
    stationCode: "219",
    stationName: "삼성(무역센터)",
    lineOrder: 26,
    journeySupported: false,
  },
  {
    id: "2:218",
    stationKey: "2:218",
    lineId: "2",
    lineName: "2호선",
    stationCode: "218",
    stationName: "종합운동장",
    lineOrder: 27,
    journeySupported: false,
  },
  {
    id: "2:217",
    stationKey: "2:217",
    lineId: "2",
    lineName: "2호선",
    stationCode: "217",
    stationName: "잠실새내",
    lineOrder: 28,
    journeySupported: false,
  },
  {
    id: "2:216",
    stationKey: "2:216",
    lineId: "2",
    lineName: "2호선",
    stationCode: "216",
    stationName: "잠실(송파구청)",
    lineOrder: 29,
    journeySupported: false,
  },
  {
    id: "2:215",
    stationKey: "2:215",
    lineId: "2",
    lineName: "2호선",
    stationCode: "215",
    stationName: "잠실나루",
    lineOrder: 30,
    journeySupported: false,
  },
  {
    id: "2:214",
    stationKey: "2:214",
    lineId: "2",
    lineName: "2호선",
    stationCode: "214",
    stationName: "강변(동서울터미널)",
    lineOrder: 31,
    journeySupported: false,
  },
  {
    id: "2:213",
    stationKey: "2:213",
    lineId: "2",
    lineName: "2호선",
    stationCode: "213",
    stationName: "구의(광진구청)",
    lineOrder: 32,
    journeySupported: false,
  },
  {
    id: "2:212",
    stationKey: "2:212",
    lineId: "2",
    lineName: "2호선",
    stationCode: "212",
    stationName: "건대입구",
    lineOrder: 33,
    journeySupported: false,
  },
  {
    id: "2:211",
    stationKey: "2:211",
    lineId: "2",
    lineName: "2호선",
    stationCode: "211",
    stationName: "성수",
    lineOrder: 34,
    journeySupported: false,
  },
  {
    id: "2:210",
    stationKey: "2:210",
    lineId: "2",
    lineName: "2호선",
    stationCode: "210",
    stationName: "뚝섬",
    lineOrder: 35,
    journeySupported: false,
  },
  {
    id: "2:244",
    stationKey: "2:244",
    lineId: "2",
    lineName: "2호선",
    stationCode: "244",
    stationName: "용답",
    lineOrder: 35,
    journeySupported: false,
  },
  {
    id: "2:209",
    stationKey: "2:209",
    lineId: "2",
    lineName: "2호선",
    stationCode: "209",
    stationName: "한양대",
    lineOrder: 36,
    journeySupported: false,
  },
  {
    id: "2:245",
    stationKey: "2:245",
    lineId: "2",
    lineName: "2호선",
    stationCode: "245",
    stationName: "신답",
    lineOrder: 36,
    journeySupported: false,
  },
  {
    id: "2:250",
    stationKey: "2:250",
    lineId: "2",
    lineName: "2호선",
    stationCode: "250",
    stationName: "용두(동대문구청)",
    lineOrder: 37,
    journeySupported: false,
  },
  {
    id: "2:208",
    stationKey: "transfer:왕십리",
    lineId: "2",
    lineName: "2호선",
    stationCode: "208",
    stationName: "왕십리",
    lineOrder: 37,
    journeySupported: false,
  },
  {
    id: "2:246",
    stationKey: "transfer:신설동",
    lineId: "2",
    lineName: "2호선",
    stationCode: "246",
    stationName: "신설동",
    lineOrder: 38,
    journeySupported: false,
  },
  {
    id: "2:207",
    stationKey: "2:207",
    lineId: "2",
    lineName: "2호선",
    stationCode: "207",
    stationName: "상왕십리",
    lineOrder: 38,
    journeySupported: false,
  },
  {
    id: "2:206",
    stationKey: "2:206",
    lineId: "2",
    lineName: "2호선",
    stationCode: "206",
    stationName: "신당",
    lineOrder: 39,
    journeySupported: false,
  },
  {
    id: "2:205",
    stationKey: "transfer:동대문역사문화공원",
    lineId: "2",
    lineName: "2호선",
    stationCode: "205",
    stationName: "동대문역사문화공원",
    lineOrder: 40,
    journeySupported: false,
  },
  {
    id: "2:204",
    stationKey: "transfer:을지로4가",
    lineId: "2",
    lineName: "2호선",
    stationCode: "204",
    stationName: "을지로4가",
    lineOrder: 41,
    journeySupported: false,
  },
  {
    id: "2:203",
    stationKey: "transfer:을지로3가",
    lineId: "2",
    lineName: "2호선",
    stationCode: "203",
    stationName: "을지로3가",
    lineOrder: 42,
    journeySupported: false,
  },
  {
    id: "2:202",
    stationKey: "2:202",
    lineId: "2",
    lineName: "2호선",
    stationCode: "202",
    stationName: "을지로입구",
    lineOrder: 43,
    journeySupported: false,
  },
  {
    id: "3:309",
    stationKey: "3:309",
    lineId: "3",
    lineName: "3호선",
    stationCode: "309",
    stationName: "대화",
    lineOrder: 1,
    journeySupported: false,
  },
  {
    id: "3:310",
    stationKey: "3:310",
    lineId: "3",
    lineName: "3호선",
    stationCode: "310",
    stationName: "주엽",
    lineOrder: 2,
    journeySupported: false,
  },
  {
    id: "3:311",
    stationKey: "3:311",
    lineId: "3",
    lineName: "3호선",
    stationCode: "311",
    stationName: "정발산",
    lineOrder: 3,
    journeySupported: false,
  },
  {
    id: "3:312",
    stationKey: "3:312",
    lineId: "3",
    lineName: "3호선",
    stationCode: "312",
    stationName: "마두",
    lineOrder: 4,
    journeySupported: false,
  },
  {
    id: "3:313",
    stationKey: "3:313",
    lineId: "3",
    lineName: "3호선",
    stationCode: "313",
    stationName: "백석",
    lineOrder: 5,
    journeySupported: false,
  },
  {
    id: "3:314",
    stationKey: "transfer:대곡",
    lineId: "3",
    lineName: "3호선",
    stationCode: "314",
    stationName: "대곡",
    lineOrder: 6,
    journeySupported: false,
  },
  {
    id: "3:315",
    stationKey: "3:315",
    lineId: "3",
    lineName: "3호선",
    stationCode: "315",
    stationName: "화정",
    lineOrder: 7,
    journeySupported: false,
  },
  {
    id: "3:316",
    stationKey: "3:316",
    lineId: "3",
    lineName: "3호선",
    stationCode: "316",
    stationName: "원당",
    lineOrder: 8,
    journeySupported: false,
  },
  {
    id: "3:317",
    stationKey: "3:317",
    lineId: "3",
    lineName: "3호선",
    stationCode: "317",
    stationName: "원흥",
    lineOrder: 9,
    journeySupported: false,
  },
  {
    id: "3:318",
    stationKey: "3:318",
    lineId: "3",
    lineName: "3호선",
    stationCode: "318",
    stationName: "삼송",
    lineOrder: 10,
    journeySupported: false,
  },
  {
    id: "3:309",
    stationKey: "3:309",
    lineId: "3",
    lineName: "3호선",
    stationCode: "309",
    stationName: "지축",
    lineOrder: 11,
    journeySupported: false,
  },
  {
    id: "3:310",
    stationKey: "3:310",
    lineId: "3",
    lineName: "3호선",
    stationCode: "310",
    stationName: "구파발",
    lineOrder: 12,
    journeySupported: false,
  },
  {
    id: "3:311",
    stationKey: "3:311",
    lineId: "3",
    lineName: "3호선",
    stationCode: "311",
    stationName: "연신내",
    lineOrder: 13,
    journeySupported: false,
  },
  {
    id: "3:312",
    stationKey: "3:312",
    lineId: "3",
    lineName: "3호선",
    stationCode: "312",
    stationName: "불광",
    lineOrder: 14,
    journeySupported: false,
  },
  {
    id: "3:313",
    stationKey: "3:313",
    lineId: "3",
    lineName: "3호선",
    stationCode: "313",
    stationName: "녹번",
    lineOrder: 15,
    journeySupported: false,
  },
  {
    id: "3:314",
    stationKey: "3:314",
    lineId: "3",
    lineName: "3호선",
    stationCode: "314",
    stationName: "홍제",
    lineOrder: 16,
    journeySupported: false,
  },
  {
    id: "3:315",
    stationKey: "3:315",
    lineId: "3",
    lineName: "3호선",
    stationCode: "315",
    stationName: "무악재",
    lineOrder: 17,
    journeySupported: false,
  },
  {
    id: "3:316",
    stationKey: "3:316",
    lineId: "3",
    lineName: "3호선",
    stationCode: "316",
    stationName: "독립문",
    lineOrder: 18,
    journeySupported: false,
  },
  {
    id: "3:317",
    stationKey: "3:317",
    lineId: "3",
    lineName: "3호선",
    stationCode: "317",
    stationName: "경복궁(정부서울청사)",
    lineOrder: 19,
    journeySupported: false,
  },
  {
    id: "3:318",
    stationKey: "3:318",
    lineId: "3",
    lineName: "3호선",
    stationCode: "318",
    stationName: "안국",
    lineOrder: 20,
    journeySupported: false,
  },
  {
    id: "3:319",
    stationKey: "transfer:종로3가",
    lineId: "3",
    lineName: "3호선",
    stationCode: "319",
    stationName: "종로3가",
    lineOrder: 21,
    journeySupported: false,
  },
  {
    id: "3:320",
    stationKey: "transfer:을지로3가",
    lineId: "3",
    lineName: "3호선",
    stationCode: "320",
    stationName: "을지로3가",
    lineOrder: 22,
    journeySupported: false,
  },
  {
    id: "3:321",
    stationKey: "3:321",
    lineId: "3",
    lineName: "3호선",
    stationCode: "321",
    stationName: "충무로",
    lineOrder: 23,
    journeySupported: false,
  },
  {
    id: "3:322",
    stationKey: "3:322",
    lineId: "3",
    lineName: "3호선",
    stationCode: "322",
    stationName: "동대입구",
    lineOrder: 24,
    journeySupported: false,
  },
  {
    id: "3:323",
    stationKey: "3:323",
    lineId: "3",
    lineName: "3호선",
    stationCode: "323",
    stationName: "약수",
    lineOrder: 25,
    journeySupported: false,
  },
  {
    id: "3:324",
    stationKey: "3:324",
    lineId: "3",
    lineName: "3호선",
    stationCode: "324",
    stationName: "금호",
    lineOrder: 26,
    journeySupported: false,
  },
  {
    id: "3:325",
    stationKey: "transfer:옥수",
    lineId: "3",
    lineName: "3호선",
    stationCode: "325",
    stationName: "옥수",
    lineOrder: 27,
    journeySupported: false,
  },
  {
    id: "3:326",
    stationKey: "3:326",
    lineId: "3",
    lineName: "3호선",
    stationCode: "326",
    stationName: "압구정",
    lineOrder: 28,
    journeySupported: false,
  },
  {
    id: "3:327",
    stationKey: "3:327",
    lineId: "3",
    lineName: "3호선",
    stationCode: "327",
    stationName: "신사",
    lineOrder: 29,
    journeySupported: false,
  },
  {
    id: "3:328",
    stationKey: "3:328",
    lineId: "3",
    lineName: "3호선",
    stationCode: "328",
    stationName: "잠원",
    lineOrder: 30,
    journeySupported: false,
  },
  {
    id: "3:329",
    stationKey: "3:329",
    lineId: "3",
    lineName: "3호선",
    stationCode: "329",
    stationName: "고속터미널",
    lineOrder: 31,
    journeySupported: false,
  },
  {
    id: "3:330",
    stationKey: "transfer:교대",
    lineId: "3",
    lineName: "3호선",
    stationCode: "330",
    stationName: "교대(법원.검찰청)",
    lineOrder: 32,
    journeySupported: false,
  },
  {
    id: "3:331",
    stationKey: "3:331",
    lineId: "3",
    lineName: "3호선",
    stationCode: "331",
    stationName: "남부터미널(예술의전당)",
    lineOrder: 33,
    journeySupported: false,
  },
  {
    id: "3:332",
    stationKey: "3:332",
    lineId: "3",
    lineName: "3호선",
    stationCode: "332",
    stationName: "양재(서초구청)",
    lineOrder: 34,
    journeySupported: false,
  },
  {
    id: "3:333",
    stationKey: "3:333",
    lineId: "3",
    lineName: "3호선",
    stationCode: "333",
    stationName: "매봉",
    lineOrder: 35,
    journeySupported: false,
  },
  {
    id: "3:334",
    stationKey: "3:334",
    lineId: "3",
    lineName: "3호선",
    stationCode: "334",
    stationName: "도곡",
    lineOrder: 36,
    journeySupported: false,
  },
  {
    id: "3:335",
    stationKey: "3:335",
    lineId: "3",
    lineName: "3호선",
    stationCode: "335",
    stationName: "대치",
    lineOrder: 37,
    journeySupported: false,
  },
  {
    id: "3:336",
    stationKey: "3:336",
    lineId: "3",
    lineName: "3호선",
    stationCode: "336",
    stationName: "학여울",
    lineOrder: 38,
    journeySupported: false,
  },
  {
    id: "3:337",
    stationKey: "3:337",
    lineId: "3",
    lineName: "3호선",
    stationCode: "337",
    stationName: "대청",
    lineOrder: 39,
    journeySupported: false,
  },
  {
    id: "3:338",
    stationKey: "3:338",
    lineId: "3",
    lineName: "3호선",
    stationCode: "338",
    stationName: "일원",
    lineOrder: 40,
    journeySupported: false,
  },
  {
    id: "3:339",
    stationKey: "3:339",
    lineId: "3",
    lineName: "3호선",
    stationCode: "339",
    stationName: "수서",
    lineOrder: 41,
    journeySupported: false,
  },
  {
    id: "3:340",
    stationKey: "3:340",
    lineId: "3",
    lineName: "3호선",
    stationCode: "340",
    stationName: "가락시장",
    lineOrder: 42,
    journeySupported: false,
  },
  {
    id: "3:341",
    stationKey: "3:341",
    lineId: "3",
    lineName: "3호선",
    stationCode: "341",
    stationName: "경찰병원",
    lineOrder: 43,
    journeySupported: false,
  },
  {
    id: "3:342",
    stationKey: "transfer:오금",
    lineId: "3",
    lineName: "3호선",
    stationCode: "342",
    stationName: "오금",
    lineOrder: 44,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K338",
    stationKey: "gyeongui-jungang:K338",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K338",
    stationName: "도라산",
    lineOrder: 1,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K337",
    stationKey: "gyeongui-jungang:K337",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K337",
    stationName: "임진강",
    lineOrder: 2,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K336",
    stationKey: "gyeongui-jungang:K336",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K336",
    stationName: "운천",
    lineOrder: 3,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K335",
    stationKey: "gyeongui-jungang:K335",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K335",
    stationName: "문산",
    lineOrder: 4,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K334",
    stationKey: "gyeongui-jungang:K334",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K334",
    stationName: "파주(두원대학)",
    lineOrder: 5,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K333",
    stationKey: "gyeongui-jungang:K333",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K333",
    stationName: "월롱(서영대학교)",
    lineOrder: 6,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K331",
    stationKey: "gyeongui-jungang:K331",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K331",
    stationName: "금촌",
    lineOrder: 7,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K330",
    stationKey: "gyeongui-jungang:K330",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K330",
    stationName: "금릉",
    lineOrder: 8,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K329",
    stationKey: "gyeongui-jungang:K329",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K329",
    stationName: "운정",
    lineOrder: 9,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K328",
    stationKey: "gyeongui-jungang:K328",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K328",
    stationName: "야당",
    lineOrder: 10,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K327",
    stationKey: "gyeongui-jungang:K327",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K327",
    stationName: "탄현",
    lineOrder: 11,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K326",
    stationKey: "gyeongui-jungang:K326",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K326",
    stationName: "일산",
    lineOrder: 12,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K325",
    stationKey: "gyeongui-jungang:K325",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K325",
    stationName: "풍산",
    lineOrder: 13,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K324",
    stationKey: "gyeongui-jungang:K324",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K324",
    stationName: "백마",
    lineOrder: 14,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K323",
    stationKey: "gyeongui-jungang:K323",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K323",
    stationName: "곡산",
    lineOrder: 15,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K322",
    stationKey: "transfer:대곡",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K322",
    stationName: "대곡",
    lineOrder: 16,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K321",
    stationKey: "gyeongui-jungang:K321",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K321",
    stationName: "능곡",
    lineOrder: 17,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K320",
    stationKey: "gyeongui-jungang:K320",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K320",
    stationName: "행신",
    lineOrder: 18,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K319",
    stationKey: "gyeongui-jungang:K319",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K319",
    stationName: "강매",
    lineOrder: 19,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K318",
    stationKey: "gyeongui-jungang:K318",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K318",
    stationName: "한국항공대",
    lineOrder: 20,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:P314",
    stationKey: "gyeongui-jungang:P314",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "P314",
    stationName: "신촌",
    lineOrder: 21,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K317",
    stationKey: "gyeongui-jungang:K317",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K317",
    stationName: "수색",
    lineOrder: 21,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:P313",
    stationKey: "transfer:서울",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "P313",
    stationName: "서울역",
    lineOrder: 22,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K316",
    stationKey: "transfer:디지털미디어시티",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K316",
    stationName: "디지털미디어시티",
    lineOrder: 22,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K315",
    stationKey: "gyeongui-jungang:K315",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K315",
    stationName: "가좌",
    lineOrder: 23,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K314",
    stationKey: "transfer:홍대입구",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K314",
    stationName: "홍대입구",
    lineOrder: 24,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K313",
    stationKey: "gyeongui-jungang:K313",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K313",
    stationName: "서강대",
    lineOrder: 25,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K312",
    stationKey: "transfer:공덕",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K312",
    stationName: "공덕",
    lineOrder: 26,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K311",
    stationKey: "gyeongui-jungang:K311",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K311",
    stationName: "효창공원앞",
    lineOrder: 27,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K110",
    stationKey: "transfer:용산",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K110",
    stationName: "용산",
    lineOrder: 28,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K111",
    stationKey: "gyeongui-jungang:K111",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K111",
    stationName: "이촌",
    lineOrder: 29,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K112",
    stationKey: "gyeongui-jungang:K112",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K112",
    stationName: "서빙고",
    lineOrder: 30,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K113",
    stationKey: "gyeongui-jungang:K113",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K113",
    stationName: "한남",
    lineOrder: 31,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K114",
    stationKey: "transfer:옥수",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K114",
    stationName: "옥수",
    lineOrder: 32,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K115",
    stationKey: "gyeongui-jungang:K115",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K115",
    stationName: "응봉",
    lineOrder: 33,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K210",
    stationKey: "transfer:왕십리",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K210",
    stationName: "왕십리",
    lineOrder: 34,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K209",
    stationKey: "transfer:청량리",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K209",
    stationName: "청량리",
    lineOrder: 35,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K118",
    stationKey: "transfer:회기",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K118",
    stationName: "회기",
    lineOrder: 36,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K119",
    stationKey: "gyeongui-jungang:K119",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K119",
    stationName: "중랑",
    lineOrder: 37,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K120",
    stationKey: "gyeongui-jungang:K120",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K120",
    stationName: "상봉",
    lineOrder: 38,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K121",
    stationKey: "gyeongui-jungang:K121",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K121",
    stationName: "망우",
    lineOrder: 39,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K122",
    stationKey: "gyeongui-jungang:K122",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K122",
    stationName: "양원(서울시북부병원)",
    lineOrder: 40,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K123",
    stationKey: "gyeongui-jungang:K123",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K123",
    stationName: "구리",
    lineOrder: 41,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K124",
    stationKey: "gyeongui-jungang:K124",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K124",
    stationName: "도농",
    lineOrder: 42,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K125",
    stationKey: "gyeongui-jungang:K125",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K125",
    stationName: "양정",
    lineOrder: 43,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K126",
    stationKey: "gyeongui-jungang:K126",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K126",
    stationName: "덕소",
    lineOrder: 44,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K127",
    stationKey: "gyeongui-jungang:K127",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K127",
    stationName: "도심",
    lineOrder: 45,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K128",
    stationKey: "gyeongui-jungang:K128",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K128",
    stationName: "팔당",
    lineOrder: 46,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K129",
    stationKey: "gyeongui-jungang:K129",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K129",
    stationName: "운길산",
    lineOrder: 47,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K130",
    stationKey: "gyeongui-jungang:K130",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K130",
    stationName: "양수",
    lineOrder: 48,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K131",
    stationKey: "gyeongui-jungang:K131",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K131",
    stationName: "신원",
    lineOrder: 49,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K132",
    stationKey: "gyeongui-jungang:K132",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K132",
    stationName: "국수",
    lineOrder: 50,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K133",
    stationKey: "gyeongui-jungang:K133",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K133",
    stationName: "아신(아세아연합신학대)",
    lineOrder: 51,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K134",
    stationKey: "gyeongui-jungang:K134",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K134",
    stationName: "오빈",
    lineOrder: 52,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K135",
    stationKey: "gyeongui-jungang:K135",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K135",
    stationName: "양평",
    lineOrder: 53,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K136",
    stationKey: "gyeongui-jungang:K136",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K136",
    stationName: "원덕(추읍산)",
    lineOrder: 54,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K137",
    stationKey: "gyeongui-jungang:K137",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K137",
    stationName: "용문",
    lineOrder: 55,
    journeySupported: false,
  },
  {
    id: "gyeongui-jungang:K138",
    stationKey: "gyeongui-jungang:K138",
    lineId: "gyeongui-jungang",
    lineName: "경의중앙선",
    stationCode: "K138",
    stationName: "지평",
    lineOrder: 56,
    journeySupported: false,
  },
  {
    id: "airport:A01",
    stationKey: "transfer:서울",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A01",
    stationName: "서울역",
    lineOrder: 1,
    journeySupported: false,
  },
  {
    id: "airport:A02",
    stationKey: "transfer:공덕",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A02",
    stationName: "공덕",
    lineOrder: 2,
    journeySupported: false,
  },
  {
    id: "airport:A03",
    stationKey: "transfer:홍대입구",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A03",
    stationName: "홍대입구",
    lineOrder: 3,
    journeySupported: false,
  },
  {
    id: "airport:A04",
    stationKey: "transfer:디지털미디어시티",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A04",
    stationName: "디지털미디어시티",
    lineOrder: 4,
    journeySupported: false,
  },
  {
    id: "airport:A042",
    stationKey: "airport:A042",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A042",
    stationName: "마곡나루",
    lineOrder: 5,
    journeySupported: false,
  },
  {
    id: "airport:A05",
    stationKey: "transfer:김포공항",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A05",
    stationName: "김포공항",
    lineOrder: 6,
    journeySupported: false,
  },
  {
    id: "airport:A06",
    stationKey: "airport:A06",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A06",
    stationName: "계양",
    lineOrder: 7,
    journeySupported: false,
  },
  {
    id: "airport:A07",
    stationKey: "airport:A07",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A07",
    stationName: "검암",
    lineOrder: 8,
    journeySupported: false,
  },
  {
    id: "airport:A071",
    stationKey: "airport:A071",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A071",
    stationName: "청라국제도시",
    lineOrder: 9,
    journeySupported: false,
  },
  {
    id: "airport:A072",
    stationKey: "airport:A072",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A072",
    stationName: "영종",
    lineOrder: 10,
    journeySupported: false,
  },
  {
    id: "airport:A08",
    stationKey: "airport:A08",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A08",
    stationName: "운서",
    lineOrder: 11,
    journeySupported: false,
  },
  {
    id: "airport:A09",
    stationKey: "airport:A09",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A09",
    stationName: "공항화물청사",
    lineOrder: 12,
    journeySupported: false,
  },
  {
    id: "airport:A10",
    stationKey: "airport:A10",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A10",
    stationName: "인천공항1터미널",
    lineOrder: 13,
    journeySupported: false,
  },
  {
    id: "airport:A11",
    stationKey: "airport:A11",
    lineId: "airport",
    lineName: "공항철도",
    stationCode: "A11",
    stationName: "인천공항2터미널",
    lineOrder: 14,
    journeySupported: false,
  },
];
