// Generated by tools/validation/build-line3-guidance.mjs.
export const LINE_3_GUIDANCE = {
  "dataVersion": "line-3.audit-2026-09-18.manual-2026-09-30",
  "verifiedAt": "2026-09-30",
  "topology": [
    "K309",
    "K310",
    "K311",
    "K312",
    "K313",
    "K314",
    "K315",
    "K316",
    "K317",
    "K318",
    "0309",
    "0310",
    "0311",
    "0312",
    "0313",
    "0314",
    "0315",
    "0316",
    "0317",
    "0318",
    "0319",
    "0320",
    "0321",
    "0322",
    "0323",
    "0324",
    "0325",
    "0326",
    "0327",
    "0328",
    "0329",
    "0330",
    "0331",
    "0332",
    "0333",
    "0334",
    "0335",
    "0336",
    "0337",
    "0338",
    "0339",
    "0340",
    "0341",
    "0342"
  ],
  "stations": [
    {
      "stationCode": "K309",
      "stationName": "대화",
      "exitNumbers": [
        "1",
        "4"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [],
      "directions": [
        {
          "toward": "주엽",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "K310",
      "stationName": "주엽",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [],
      "directions": [
        {
          "toward": "대화",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "정발산",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "K311",
      "stationName": "정발산",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [],
      "directions": [
        {
          "toward": "주엽",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "마두",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "K312",
      "stationName": "마두",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [],
      "directions": [
        {
          "toward": "정발산",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "백석",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "K313",
      "stationName": "백석",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [],
      "directions": [
        {
          "toward": "마두",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "대곡",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "K314",
      "stationName": "대곡",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [],
      "directions": [
        {
          "toward": "백석",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "화정",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "K315",
      "stationName": "화정",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [],
      "directions": [
        {
          "toward": "대곡",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "원당",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "K316",
      "stationName": "원당",
      "exitNumbers": [
        "3",
        "5"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [],
      "directions": [
        {
          "toward": "화정",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "원흥",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "K317",
      "stationName": "원흥",
      "exitNumbers": [
        "2",
        "4",
        "5",
        "8"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [],
      "directions": [
        {
          "toward": "원당",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "삼송",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "K318",
      "stationName": "삼송",
      "exitNumbers": [
        "5",
        "6",
        "8"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [],
      "directions": [
        {
          "toward": "원흥",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "지축",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "0309",
      "stationName": "지축",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0309-live-1",
          "name": "승강기)엘리베이터-지축 섬식(상) 2-1 내부#1",
          "operatingSection": "1F-2F",
          "location": "삼송 방면9-3, 구파발 방면2-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "삼송",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "9-3"
          ],
          "doorGaps": [
            {
              "door": "9-3",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "구파발",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "2-2"
          ],
          "doorGaps": [
            {
              "door": "2-2",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0310",
      "stationName": "구파발",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0310-live-1",
          "name": "승강기)엘리베이터-구파발 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0310-live-2",
          "name": "승강기)엘리베이터-구파발 섬식(상) 5-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "지축 방면5-3, 연신내 방면6-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "지축",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "5-3"
          ],
          "doorGaps": [
            {
              "door": "5-3",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "연신내",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "6-2"
          ],
          "doorGaps": [
            {
              "door": "6-2",
              "gap": {
                "distanceCm": 8.8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0311",
      "stationName": "연신내",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0311-live-1",
          "name": "승강기)엘리베이터-연신내 섬식(상) 6-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "구파발 방면6-1, 불광 방면5-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "구파발",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "6-1"
          ],
          "doorGaps": [
            {
              "door": "6-1",
              "gap": {
                "distanceCm": 4,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "불광",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0312",
      "stationName": "불광",
      "exitNumbers": [
        "1",
        "8"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0312-live-1",
          "name": "승강기)엘리베이터-불광 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0312-live-2",
          "name": "승강기)엘리베이터-불광 상행 3-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "연신내 방면3-3",
          "kind": "platform"
        },
        {
          "id": "0312-live-3",
          "name": "승강기)엘리베이터-불광 하행 8-2 내부#2",
          "operatingSection": "B2-B1",
          "location": "녹번 방면8-2",
          "kind": "platform"
        },
        {
          "id": "0312-live-4",
          "name": "승강기)엘리베이터-불광(3) 3번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "3번 출입구",
          "kind": "surface"
        }
      ],
      "directions": [
        {
          "toward": "연신내",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": {
                "distanceCm": 13,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "녹번",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-2"
          ],
          "doorGaps": [
            {
              "door": "8-2",
              "gap": {
                "distanceCm": 14,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0313",
      "stationName": "녹번",
      "exitNumbers": [
        "1",
        "3"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0313-live-1",
          "name": "승강기)엘리베이터-녹번 1번출구 외부#2",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0313-live-2",
          "name": "승강기)엘리베이터-녹번 3번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0313-live-3",
          "name": "승강기)엘리베이터-녹번 섬식(상) 3-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "불광 방면3-1, 홍제 방면8-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "불광",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "홍제",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0314",
      "stationName": "홍제",
      "exitNumbers": [
        "4"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0314-live-1",
          "name": "승강기)엘리베이터-홍제 1번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0314-live-2",
          "name": "승강기)엘리베이터-홍제 4번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0314-live-3",
          "name": "승강기)엘리베이터-홍제 섬식(상) 3-4 내부#1",
          "operatingSection": "B3-B2",
          "location": "녹번 방면3-4, 무악재 방면8-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "녹번",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 12,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "무악재",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "8-1"
          ],
          "doorGaps": [
            {
              "door": "8-1",
              "gap": {
                "distanceCm": 12,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0315",
      "stationName": "무악재",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0315-live-1",
          "name": "승강기)엘리베이터-무악재 1번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0315-live-2",
          "name": "승강기)엘리베이터-무악재 상행 3-3 내부#1",
          "operatingSection": "B3-B2",
          "location": "홍제 방면3-3",
          "kind": "platform"
        },
        {
          "id": "0315-live-3",
          "name": "승강기)엘리베이터-무악재 하행 8-2 내부#2",
          "operatingSection": "B3-B2",
          "location": "독립문 방면8-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "홍제",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": {
                "distanceCm": 14.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "독립문",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-2"
          ],
          "doorGaps": [
            {
              "door": "8-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0316",
      "stationName": "독립문",
      "exitNumbers": [
        "4"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0316-live-1",
          "name": "승강기)엘리베이터-독립문 4번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0316-live-2",
          "name": "승강기)엘리베이터-독립문 섬식(상) 9-1 내부#1",
          "operatingSection": "B3-B2",
          "location": "무악재 방면9-1, 경복궁 방면2-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "무악재",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "9-1"
          ],
          "doorGaps": [
            {
              "door": "9-1",
              "gap": {
                "distanceCm": 12,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "경복궁",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "2-4"
          ],
          "doorGaps": [
            {
              "door": "2-4",
              "gap": {
                "distanceCm": 11.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0317",
      "stationName": "경복궁",
      "exitNumbers": [
        "4"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0317-live-1",
          "name": "승강기)엘리베이터-경복궁 4번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0317-live-2",
          "name": "승강기)엘리베이터-경복궁 섬식(상) 6-2 내부#1",
          "operatingSection": "B3-B2",
          "location": "독립문 방면6-2, 안국 방면5-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "독립문",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "6-2"
          ],
          "doorGaps": [
            {
              "door": "6-2",
              "gap": {
                "distanceCm": 16,
                "level": "red",
                "label": "추천하지 않음"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "안국",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "5-3"
          ],
          "doorGaps": [
            {
              "door": "5-3",
              "gap": {
                "distanceCm": 14,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0318",
      "stationName": "안국",
      "exitNumbers": [
        "6"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0318-live-1",
          "name": "승강기)엘리베이터-안국 6번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0318-live-2",
          "name": "승강기)엘리베이터-안국 섬식(상) 3-2 내부#1",
          "operatingSection": "B3-B2",
          "location": "경복궁 방면3-2, 종로3가 방면8-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "경복궁",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 12,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "종로3가",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0319",
      "stationName": "종로3가",
      "exitNumbers": [
        "2-1",
        "8"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0319-live-1",
          "name": "승강기)엘리베이터-종로3가(3) 7번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "8번 출입구",
          "kind": "surface"
        },
        {
          "id": "0319-live-2",
          "name": "승강기)엘리베이터-종로3가(3) 섬식(상) 4-4 내부#1",
          "operatingSection": "B4-B2",
          "location": "안국 방면4-3, 을지로3가 방면7-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "안국",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 9.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "을지로 3가",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "7-1"
          ],
          "doorGaps": [
            {
              "door": "7-1",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "지축",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 9.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "오금",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "7-1"
          ],
          "doorGaps": [
            {
              "door": "7-1",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0320",
      "stationName": "을지로3가",
      "exitNumbers": [
        "10",
        "12"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0320-live-1",
          "name": "승강기)엘리베이터-을지로3가(3) 10번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "10번 출입구",
          "kind": "surface"
        },
        {
          "id": "0320-live-2",
          "name": "승강기)엘리베이터-을지로3가(3) 섬식(상) 6-3 내부#1",
          "operatingSection": "B3-B2-B1",
          "location": "종로3가 방면6-3, 충무로 방면5-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "종로3가",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "6-3"
          ],
          "doorGaps": [
            {
              "door": "6-3",
              "gap": {
                "distanceCm": 9.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "충무로",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "5-2"
          ],
          "doorGaps": [
            {
              "door": "5-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0321",
      "stationName": "충무로",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [],
      "directions": [
        {
          "toward": "을지로3가",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "동대입구",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "0322",
      "stationName": "동대입구",
      "exitNumbers": [
        "6"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0322-live-1",
          "name": "승강기)엘리베이터-동대입구 2번 출구측 외부#2",
          "operatingSection": "B2-1F",
          "location": "2번 출입구",
          "kind": "surface"
        },
        {
          "id": "0322-live-2",
          "name": "승강기)엘리베이터-동대입구 5번 출구쪽 내부#2",
          "operatingSection": "B2-B1",
          "location": "대합실(F계단 측, 3~5번 출입구 방향)",
          "kind": "surface"
        },
        {
          "id": "0322-live-3",
          "name": "승강기)엘리베이터-동대입구 6번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0322-live-4",
          "name": "승강기)엘리베이터-동대입구 섬식(상) 3-3 내부#1",
          "operatingSection": "B3-B2",
          "location": "충무로 방면3-1, 약수 방면8-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "충무로",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "약수",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 20,
                "level": "red",
                "label": "추천하지 않음"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0323",
      "stationName": "약수",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0323-live-1",
          "name": "승강기)엘리베이터-약수 3번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0323-live-2",
          "name": "승강기)엘리베이터-약수 섬식(상) 8-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "동대입구 방면8-4, 금호 방면3-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "동대입구",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "금호",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 10.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0324",
      "stationName": "금호",
      "exitNumbers": [
        "2",
        "3"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0324-live-1",
          "name": "승강기)엘리베이터-금호 2번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "2번 출입구",
          "kind": "surface"
        },
        {
          "id": "0324-live-2",
          "name": "승강기)엘리베이터-금호 3번출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "3번 출입구 측",
          "kind": "surface"
        },
        {
          "id": "0324-live-3",
          "name": "승강기)엘리베이터-금호 섬식(상) 3-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "약수 방면3-2, 옥수 방면8-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "약수",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "옥수",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 17,
                "level": "red",
                "label": "추천하지 않음"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0325",
      "stationName": "옥수",
      "exitNumbers": [
        "4"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0325-live-1",
          "name": "승강기)엘리베이터-옥수 4,5번출구측 외부#1",
          "operatingSection": "1F-2F",
          "location": "5,6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0325-live-2",
          "name": "승강기)엘리베이터-옥수 상행 10-1 내부#1",
          "operatingSection": "2F-3F",
          "location": "금호 방면10-1",
          "kind": "platform"
        },
        {
          "id": "0325-live-3",
          "name": "승강기)엘리베이터-옥수 하행 1-2 내부#2",
          "operatingSection": "2F-3F",
          "location": "압구정 방면1-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "금호",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "10-1"
          ],
          "doorGaps": [
            {
              "door": "10-1",
              "gap": {
                "distanceCm": 18,
                "level": "red",
                "label": "추천하지 않음"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "압구정",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "1-2"
          ],
          "doorGaps": [
            {
              "door": "1-2",
              "gap": {
                "distanceCm": 6.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0326",
      "stationName": "압구정",
      "exitNumbers": [
        "2",
        "3"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0326-live-1",
          "name": "승강기)엘리베이터-압구정 2번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0326-live-2",
          "name": "승강기)엘리베이터-압구정 상행 8-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "옥수 방면8-2",
          "kind": "platform"
        },
        {
          "id": "0326-live-3",
          "name": "승강기)엘리베이터-압구정 외부#1",
          "operatingSection": "B1-1F",
          "location": "2번 출입구",
          "kind": "surface"
        },
        {
          "id": "0326-live-4",
          "name": "승강기)엘리베이터-압구정 하행 3-2 내부#2",
          "operatingSection": "B2-B1",
          "location": "신사 방면3-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "옥수",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-2"
          ],
          "doorGaps": [
            {
              "door": "8-2",
              "gap": {
                "distanceCm": 18,
                "level": "red",
                "label": "추천하지 않음"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "신사",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0327",
      "stationName": "신사",
      "exitNumbers": [
        "1",
        "6",
        "8"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0327-live-1",
          "name": "승강기)엘리베이터-신사 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0327-live-2",
          "name": "승강기)엘리베이터-신사 8번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "8번 출입구",
          "kind": "surface"
        },
        {
          "id": "0327-live-3",
          "name": "승강기)엘리베이터-신사 상행 3-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "압구정 방면3-1",
          "kind": "platform"
        },
        {
          "id": "0327-live-4",
          "name": "승강기)엘리베이터-신사 하행 8-3 내부#2",
          "operatingSection": "B2-B1",
          "location": "잠원 방면8-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "압구정",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 3,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "잠원",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0328",
      "stationName": "잠원",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0328-live-1",
          "name": "승강기)엘리베이터-잠원 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0328-live-2",
          "name": "승강기)엘리베이터-잠원 상행 3-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "신사 방면3-3",
          "kind": "platform"
        },
        {
          "id": "0328-live-3",
          "name": "승강기)엘리베이터-잠원 하행 8-2 내부#2",
          "operatingSection": "B2-B1",
          "location": "고속터미널 방면8-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "신사",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": {
                "distanceCm": 6.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "고속터미널",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "8-2"
          ],
          "doorGaps": [
            {
              "door": "8-2",
              "gap": {
                "distanceCm": 12,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0329",
      "stationName": "고속터미널",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0329-live-1",
          "name": "승강기)엘리베이터-고속터미널 상행 8-2 내부#1",
          "operatingSection": "B3-B2",
          "location": "잠원 방면8-2",
          "kind": "platform"
        },
        {
          "id": "0329-live-2",
          "name": "승강기)엘리베이터-고속터미널 하행 3-3 내부#2",
          "operatingSection": "B3-B2",
          "location": "교대 방면3-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "잠원",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "8-2"
          ],
          "doorGaps": [
            {
              "door": "8-2",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "교대",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0330",
      "stationName": "교대",
      "exitNumbers": [
        "12",
        "13"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0330-live-1",
          "name": "승강기)엘리베이터-교대(3) #13출입구 외부엘리베이터 1호기",
          "operatingSection": "B1-1F",
          "location": "13번 출입구",
          "kind": "surface"
        },
        {
          "id": "0330-live-2",
          "name": "승강기)엘리베이터-교대(3) 섬식(상) 4-2 내부#1",
          "operatingSection": "B3-B2-B1",
          "location": "고속터미널 방면4-2, 남부터미널 방면7-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "고속터미널",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "4-2"
          ],
          "doorGaps": [
            {
              "door": "4-2",
              "gap": {
                "distanceCm": 3.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "남부터미널",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "7-3"
          ],
          "doorGaps": [
            {
              "door": "7-3",
              "gap": {
                "distanceCm": 12,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0331",
      "stationName": "남부터미널",
      "exitNumbers": [
        "5"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0331-live-1",
          "name": "승강기)엘리베이터-남부터미널 5번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "5번 출입구",
          "kind": "surface"
        },
        {
          "id": "0331-live-2",
          "name": "승강기)엘리베이터-남부터미널 상행 3-2 내부#1",
          "operatingSection": "B3-B2",
          "location": "교대 방면3-2",
          "kind": "platform"
        },
        {
          "id": "0331-live-3",
          "name": "승강기)엘리베이터-남부터미널 하행 8-2 내부#2",
          "operatingSection": "B3-B2",
          "location": "양재 방면8-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "교대",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "양재",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-2"
          ],
          "doorGaps": [
            {
              "door": "8-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0332",
      "stationName": "양재",
      "exitNumbers": [
        "1",
        "4",
        "7",
        "10",
        "11"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0332-live-1",
          "name": "승강기)엘리베이터 양재 1번 출입구 외부#3",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0332-live-2",
          "name": "승강기)엘리베이터-양재 11번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "11번 출입구",
          "kind": "surface"
        },
        {
          "id": "0332-live-3",
          "name": "승강기)엘리베이터-양재 4번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0332-live-4",
          "name": "승강기)엘리베이터-양재 상행 3-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "남부터미널 방면3-1",
          "kind": "platform"
        },
        {
          "id": "0332-live-5",
          "name": "승강기)엘리베이터-양재 하행 8-4 내부#2",
          "operatingSection": "B2-B1",
          "location": "매봉 방면8-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "남부터미널",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "매봉",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 10.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0333",
      "stationName": "매봉",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0333-live-1",
          "name": "승강기)엘리베이터-매봉 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0333-live-2",
          "name": "승강기)엘리베이터-매봉 상행 5-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "양재 방면5-4",
          "kind": "platform"
        },
        {
          "id": "0333-live-3",
          "name": "승강기)엘리베이터-매봉 하행 6-1 내부#2",
          "operatingSection": "B2-B1",
          "location": "도곡 방면6-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "양재",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 10.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "도곡",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "6-1"
          ],
          "doorGaps": [
            {
              "door": "6-1",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0334",
      "stationName": "도곡",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [],
      "directions": [
        {
          "toward": "매봉",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "대치",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "0335",
      "stationName": "대치",
      "exitNumbers": [
        "7"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0335-live-1",
          "name": "승강기)엘리베이터-대치 7번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "7번 출입구",
          "kind": "surface"
        },
        {
          "id": "0335-live-2",
          "name": "승강기)엘리베이터-대치 섬식(상) 1-1 내부#1",
          "operatingSection": "B3-B1",
          "location": "도곡 방면1-1, 학여울 방면10-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "도곡",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "1-1"
          ],
          "doorGaps": [
            {
              "door": "1-1",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "학여울",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "10-4"
          ],
          "doorGaps": [
            {
              "door": "10-4",
              "gap": {
                "distanceCm": 4,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0336",
      "stationName": "학여울",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0336-live-1",
          "name": "승강기)엘리베이터-학여울 1번 출구측 외부#1",
          "operatingSection": "B4-B2-B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0336-live-2",
          "name": "승강기)엘리베이터-학여울 상행 5-4 내부#1",
          "operatingSection": "B5-B4",
          "location": "대치 방면5-4",
          "kind": "platform"
        },
        {
          "id": "0336-live-3",
          "name": "승강기)엘리베이터-학여울 하행 6-1 내부#2",
          "operatingSection": "B5-B4",
          "location": "대청 방면6-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "대치",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "대청",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "6-1"
          ],
          "doorGaps": [
            {
              "door": "6-1",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0337",
      "stationName": "대청",
      "exitNumbers": [
        "8"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0337-live-1",
          "name": "승강기)엘리베이터-대청 8번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "8번 출입구",
          "kind": "surface"
        },
        {
          "id": "0337-live-2",
          "name": "승강기)엘리베이터-대청 상행 4-4 내부#1",
          "operatingSection": "B3-B2",
          "location": "학여울 방면4-4",
          "kind": "platform"
        },
        {
          "id": "0337-live-3",
          "name": "승강기)엘리베이터-대청 하행 7-1 내부#2",
          "operatingSection": "B3-B2",
          "location": "일원 방면7-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "학여울",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "일원",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "7-1"
          ],
          "doorGaps": [
            {
              "door": "7-1",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0338",
      "stationName": "일원",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0338-live-1",
          "name": "승강기)엘리베이터-일원 1번 출구측 외부#2",
          "operatingSection": "B2-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0338-live-2",
          "name": "승강기)엘리베이터-일원 1번 출구측 외부#3",
          "operatingSection": "B2-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0338-live-3",
          "name": "승강기)엘리베이터-일원 상행 6-3 내부#1",
          "operatingSection": "B3-B2",
          "location": "대청 방면6-3",
          "kind": "platform"
        },
        {
          "id": "0338-live-4",
          "name": "승강기)엘리베이터-일원 하행 5-2 내부#2",
          "operatingSection": "B3-B2",
          "location": "수서 방면5-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "대청",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "6-3"
          ],
          "doorGaps": [
            {
              "door": "6-3",
              "gap": {
                "distanceCm": 10.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "수서",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "5-2"
          ],
          "doorGaps": [
            {
              "door": "5-2",
              "gap": {
                "distanceCm": 12.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0339",
      "stationName": "수서",
      "exitNumbers": [
        "1",
        "5"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0339-live-1",
          "name": "승강기)엘리베이터-수서 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0339-live-2",
          "name": "승강기)엘리베이터-수서 5번출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "5번 출입구",
          "kind": "surface"
        },
        {
          "id": "0339-live-3",
          "name": "승강기)엘리베이터-수서 상행 8-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "가락시장 방면3-2",
          "kind": "platform"
        },
        {
          "id": "0339-live-4",
          "name": "승강기)엘리베이터-수서 하행 3-2 내부#2",
          "operatingSection": "B2-B1",
          "location": "일원 방면8-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "일원",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 10.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "가락시장",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0340",
      "stationName": "가락시장",
      "exitNumbers": [
        "1",
        "4",
        "7"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0340-live-1",
          "name": "승강기)엘리베이터-가락시장(3) 7번 출구측 외부#1",
          "operatingSection": "B2-B1-1F",
          "location": "7번 출입구",
          "kind": "surface"
        },
        {
          "id": "0340-live-2",
          "name": "승강기)엘리베이터-가락시장(3) 상행 8-2 내부#1",
          "operatingSection": "B4-B3-B2",
          "location": "수서 방면8-2",
          "kind": "platform"
        },
        {
          "id": "0340-live-3",
          "name": "승강기)엘리베이터-가락시장(3) 하행 3-2 내부#2",
          "operatingSection": "B4-B3-B2",
          "location": "경찰병원 방면3-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "수서",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-2"
          ],
          "doorGaps": [
            {
              "door": "8-2",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "경찰병원",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0341",
      "stationName": "경찰병원",
      "exitNumbers": [
        "1",
        "3"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0341-live-1",
          "name": "승강기)엘리베이터-경찰병원 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0341-live-2",
          "name": "승강기)엘리베이터-경찰병원 3번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0341-live-3",
          "name": "승강기)엘리베이터-경찰병원 상행 4-2 내부#1",
          "operatingSection": "B3-B1",
          "location": "가락시장 방면4-2",
          "kind": "platform"
        },
        {
          "id": "0341-live-4",
          "name": "승강기)엘리베이터-경찰병원 하행 7-3 내부#2",
          "operatingSection": "B3-B1",
          "location": "오금 방면 7-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "가락시장",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "4-2"
          ],
          "doorGaps": [
            {
              "door": "4-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "오금",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "7-3"
          ],
          "doorGaps": [
            {
              "door": "7-3",
              "gap": {
                "distanceCm": 15,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0342",
      "stationName": "오금",
      "exitNumbers": [
        "5",
        "7"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0342-live-1",
          "name": "승강기)엘리베이터-오금 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0342-live-2",
          "name": "승강기)엘리베이터-오금 상행 5-1 내부#1",
          "operatingSection": "B4-B3-B1",
          "location": "경찰병원 방면5-1",
          "kind": "platform"
        },
        {
          "id": "0342-live-3",
          "name": "승강기)엘리베이터-오금 하행 6-4 내부#2",
          "operatingSection": "B4-B3-B1",
          "location": "오금 방면6-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "경찰병원",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    }
  ]
} as const;
