// Generated by tools/kric/update-line5-accessibility-guidance.mjs.
export const LINE_5_GUIDANCE = {
  "dataVersion": "2026-09-28T01:11:11.728Z.manual-2026-09-28",
  "verifiedAt": "2026-09-28",
  "policy": {
    "missingAccessibilityData": "show_general_route_with_unverified_warning",
    "yellowGap": "warn_and_recommend",
    "redGap": "exclude",
    "directionLabel": "terminal_first",
    "adjacentDoorPriority": [
      "farther_from_stairs",
      "farther_from_escalators_when_location_is_known",
      "smaller_platform_gap"
    ]
  },
  "topologies": [
    [
      "2511",
      "2512",
      "2513",
      "2514",
      "2515",
      "2516",
      "2517",
      "2518",
      "2519",
      "2520",
      "2521",
      "2522",
      "2523",
      "2524",
      "2525",
      "2526",
      "2527",
      "2528",
      "2529",
      "2530",
      "2531",
      "2532",
      "2533",
      "2534",
      "2535",
      "2536",
      "2537",
      "2538",
      "2539",
      "2540",
      "2541",
      "2542",
      "2543",
      "2544",
      "2545",
      "2546",
      "2547",
      "2548",
      "2549",
      "2550",
      "2551",
      "2552",
      "2553",
      "2554",
      "2562",
      "2563",
      "2564",
      "2565",
      "2566"
    ],
    [
      "2511",
      "2512",
      "2513",
      "2514",
      "2515",
      "2516",
      "2517",
      "2518",
      "2519",
      "2520",
      "2521",
      "2522",
      "2523",
      "2524",
      "2525",
      "2526",
      "2527",
      "2528",
      "2529",
      "2530",
      "2531",
      "2532",
      "2533",
      "2534",
      "2535",
      "2536",
      "2537",
      "2538",
      "2539",
      "2540",
      "2541",
      "2542",
      "2543",
      "2544",
      "2545",
      "2546",
      "2547",
      "2548",
      "2549",
      "2555",
      "2556",
      "2557",
      "2558",
      "2559",
      "2560",
      "2561"
    ]
  ],
  "stations": [
    {
      "stationCode": "2511",
      "stationName": "방화",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "방화",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-1"
          ],
          "doorGaps": [
            {
              "door": "4-1",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "개화산",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2512",
      "stationName": "개화산",
      "exitNumbers": [
        "1",
        "2"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "방화",
          "platformNumber": "1",
          "recommendedDoors": [
            "2-3"
          ],
          "doorGaps": [
            {
              "door": "2-3",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "김포공항",
          "platformNumber": "2",
          "recommendedDoors": [
            "7-2"
          ],
          "doorGaps": [
            {
              "door": "7-2",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2513",
      "stationName": "김포공항",
      "exitNumbers": [
        "3",
        "4"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "개화산",
          "platformNumber": "1",
          "recommendedDoors": [
            "6-3"
          ],
          "doorGaps": [
            {
              "door": "6-3",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "송정",
          "platformNumber": "2",
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 12,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2514",
      "stationName": "송정",
      "exitNumbers": [
        "2",
        "3"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "김포공항",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4",
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "마곡",
          "platformNumber": "2",
          "recommendedDoors": [
            "3-4",
            "4-1",
            "4-4",
            "5-1",
            "5-4",
            "6-1"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "4-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "6-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2515",
      "stationName": "마곡",
      "exitNumbers": [
        "2",
        "3",
        "5",
        "7"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "송정",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "발산",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2516",
      "stationName": "발산",
      "exitNumbers": [
        "7"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "마곡",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 13,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "우장산",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 3,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2517",
      "stationName": "우장산",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "발산",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-2"
          ],
          "doorGaps": [
            {
              "door": "4-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "화곡",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-3"
          ],
          "doorGaps": [
            {
              "door": "5-3",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2518",
      "stationName": "화곡",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "우장산",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-2"
          ],
          "doorGaps": [
            {
              "door": "5-2",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "까치산",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2519",
      "stationName": "까치산",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "api_missing",
      "directions": []
    },
    {
      "stationCode": "2520",
      "stationName": "신정",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "까치산",
          "platformNumber": "1",
          "recommendedDoors": [
            "7-4"
          ],
          "doorGaps": [
            {
              "door": "7-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "목동",
          "platformNumber": "2",
          "recommendedDoors": [
            "1-4"
          ],
          "doorGaps": [
            {
              "door": "1-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2521",
      "stationName": "목동",
      "exitNumbers": [
        "5"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "신정",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "오목교",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 13,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2522",
      "stationName": "오목교",
      "exitNumbers": [
        "7"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "목동",
          "platformNumber": "1",
          "recommendedDoors": [
            "7-1"
          ],
          "doorGaps": [
            {
              "door": "7-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "양평",
          "platformNumber": "2",
          "recommendedDoors": [
            "2-3"
          ],
          "doorGaps": [
            {
              "door": "2-3",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2523",
      "stationName": "양평",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "오목교",
          "platformNumber": "1",
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "영등포구청",
          "platformNumber": "2",
          "recommendedDoors": [
            "6-2"
          ],
          "doorGaps": [
            {
              "door": "6-2",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2524",
      "stationName": "영등포구청",
      "exitNumbers": [
        "7"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "양평",
          "platformNumber": "1",
          "recommendedDoors": [
            "6-4",
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "6-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "영등포시장",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2525",
      "stationName": "영등포시장",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "영등포구청",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "신길",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-2"
          ],
          "doorGaps": [
            {
              "door": "5-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2526",
      "stationName": "신길",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "영등포시장",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-3"
          ],
          "doorGaps": [
            {
              "door": "5-3",
              "gap": {
                "distanceCm": 4,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "여의도",
          "platformNumber": "2",
          "recommendedDoors": [
            "1-1"
          ],
          "doorGaps": [
            {
              "door": "1-1",
              "gap": {
                "distanceCm": 13,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2527",
      "stationName": "여의도",
      "exitNumbers": [
        "2",
        "3"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "신길",
          "platformNumber": "1",
          "recommendedDoors": [
            "6-4"
          ],
          "doorGaps": [
            {
              "door": "6-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "여의나루",
          "platformNumber": "2",
          "recommendedDoors": [
            "6-4"
          ],
          "doorGaps": [
            {
              "door": "6-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2528",
      "stationName": "여의나루",
      "exitNumbers": [
        "4"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "여의도",
          "platformNumber": "1",
          "recommendedDoors": [
            "6-2"
          ],
          "doorGaps": [
            {
              "door": "6-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "마포",
          "platformNumber": "2",
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2529",
      "stationName": "마포",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "여의나루",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "공덕",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2530",
      "stationName": "공덕",
      "exitNumbers": [
        "2",
        "5"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "마포",
          "platformNumber": "1",
          "recommendedDoors": [
            "1-1"
          ],
          "doorGaps": [
            {
              "door": "1-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "애오개",
          "platformNumber": "2",
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2531",
      "stationName": "애오개",
      "exitNumbers": [
        "2",
        "3"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "공덕",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "충정로",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2532",
      "stationName": "충정로",
      "exitNumbers": [
        "8"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "애오개",
          "platformNumber": "1",
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 13,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "서대문",
          "platformNumber": "2",
          "recommendedDoors": [
            "6-1"
          ],
          "doorGaps": [
            {
              "door": "6-1",
              "gap": {
                "distanceCm": 6,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2533",
      "stationName": "서대문",
      "exitNumbers": [
        "2",
        "6"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "충정로",
          "platformNumber": "1",
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 6,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "광화문",
          "platformNumber": "2",
          "recommendedDoors": [
            "6-3"
          ],
          "doorGaps": [
            {
              "door": "6-3",
              "gap": {
                "distanceCm": 14,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2534",
      "stationName": "광화문",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "서대문",
          "platformNumber": "1",
          "recommendedDoors": [
            "1-1"
          ],
          "doorGaps": [
            {
              "door": "1-1",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "종로3가",
          "platformNumber": "2",
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2535",
      "stationName": "종로3가",
      "exitNumbers": [
        "8"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "광화문",
          "platformNumber": "1",
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "을지로4가",
          "platformNumber": "2",
          "recommendedDoors": [
            "1-1"
          ],
          "doorGaps": [
            {
              "door": "1-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2536",
      "stationName": "을지로4가",
      "exitNumbers": [
        "8"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "종로3가",
          "platformNumber": "1",
          "recommendedDoors": [
            "10-4"
          ],
          "doorGaps": [
            {
              "door": "10-4",
              "gap": null
            }
          ],
          "accessibilityVerified": false,
          "warning": "승강장 이격거리 미확인"
        },
        {
          "toward": "동대문역사문화공원",
          "platformNumber": "2",
          "recommendedDoors": [
            "1-1"
          ],
          "doorGaps": [
            {
              "door": "1-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2537",
      "stationName": "동대문역사문화공원",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "을지로4가",
          "platformNumber": "1",
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "청구",
          "platformNumber": "2",
          "recommendedDoors": [
            "1-1"
          ],
          "doorGaps": [
            {
              "door": "1-1",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2538",
      "stationName": "청구",
      "exitNumbers": [
        "1",
        "3"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "동대문역사문화공원",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 4,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "신금호",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2539",
      "stationName": "신금호",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "청구",
          "platformNumber": "1",
          "recommendedDoors": [
            "1-1"
          ],
          "doorGaps": [
            {
              "door": "1-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "행당",
          "platformNumber": "2",
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 3,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2540",
      "stationName": "행당",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "신금호",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "왕십리",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2541",
      "stationName": "왕십리",
      "exitNumbers": [
        "4",
        "6-1"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "행당",
          "platformNumber": "1",
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "마장",
          "platformNumber": "2",
          "recommendedDoors": [
            "6-2"
          ],
          "doorGaps": [
            {
              "door": "6-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2542",
      "stationName": "마장",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "왕십리",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "답십리",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-2"
          ],
          "doorGaps": [
            {
              "door": "5-2",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2543",
      "stationName": "답십리",
      "exitNumbers": [
        "2",
        "6"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "마장",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "장한평",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2544",
      "stationName": "장한평",
      "exitNumbers": [
        "1",
        "7"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "답십리",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "군자",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2545",
      "stationName": "군자",
      "exitNumbers": [
        "4",
        "7"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "장한평",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "아차산",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-2"
          ],
          "doorGaps": [
            {
              "door": "4-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2546",
      "stationName": "아차산",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "군자",
          "platformNumber": "1",
          "recommendedDoors": [
            "6-1"
          ],
          "doorGaps": [
            {
              "door": "6-1",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "광나루",
          "platformNumber": "2",
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": {
                "distanceCm": 6,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2547",
      "stationName": "광나루",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "아차산",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "천호",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2548",
      "stationName": "천호",
      "exitNumbers": [
        "6"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "광나루",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "강동",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-1"
          ],
          "doorGaps": [
            {
              "door": "4-1",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2549",
      "stationName": "강동",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "둔촌동",
          "platformNumber": null,
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2550",
      "stationName": "길동",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "강동",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "굽은다리",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2555",
      "stationName": "둔촌동",
      "exitNumbers": [
        "2",
        "4"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "강동",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "올림픽공원",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2551",
      "stationName": "굽은다리",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "길동",
          "platformNumber": "1",
          "recommendedDoors": [
            "6-2"
          ],
          "doorGaps": [
            {
              "door": "6-2",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "명일",
          "platformNumber": "2",
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2556",
      "stationName": "올림픽공원",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "둔촌동",
          "platformNumber": "1",
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "방이",
          "platformNumber": "2",
          "recommendedDoors": [
            "6-3"
          ],
          "doorGaps": [
            {
              "door": "6-3",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2557",
      "stationName": "방이",
      "exitNumbers": [
        "1",
        "3"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "올림픽공원",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "오금",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2552",
      "stationName": "명일",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "굽은다리",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-2"
          ],
          "doorGaps": [
            {
              "door": "5-2",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "고덕",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2558",
      "stationName": "오금",
      "exitNumbers": [
        "1",
        "5"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "방이",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "개롱",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2553",
      "stationName": "고덕",
      "exitNumbers": [
        "2",
        "5"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "명일",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-1"
          ],
          "doorGaps": [
            {
              "door": "4-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "상일동",
          "platformNumber": "2",
          "recommendedDoors": [
            "6-1"
          ],
          "doorGaps": [
            {
              "door": "6-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2559",
      "stationName": "개롱",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "오금",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "거여",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2554",
      "stationName": "상일동",
      "exitNumbers": [
        "1",
        "4",
        "6",
        "7"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "고덕",
          "platformNumber": "1",
          "recommendedDoors": [
            "6-1"
          ],
          "doorGaps": [
            {
              "door": "6-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "강일",
          "platformNumber": "2",
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2562",
      "stationName": "강일",
      "exitNumbers": [
        "1",
        "2",
        "3",
        "4"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "상일동",
          "platformNumber": "1",
          "recommendedDoors": [
            "1-2",
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "1-2",
              "gap": {
                "distanceCm": 5.5,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 7.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "미사",
          "platformNumber": "2",
          "recommendedDoors": [
            "1-2",
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "1-2",
              "gap": {
                "distanceCm": 7.5,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 9.8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2560",
      "stationName": "거여",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "개롱",
          "platformNumber": "1",
          "recommendedDoors": [
            "6-2"
          ],
          "doorGaps": [
            {
              "door": "6-2",
              "gap": {
                "distanceCm": 3,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "마천",
          "platformNumber": "2",
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 14,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2561",
      "stationName": "마천",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "거여",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "마천",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-2"
          ],
          "doorGaps": [
            {
              "door": "5-2",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2563",
      "stationName": "미사",
      "exitNumbers": [
        "1",
        "6"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "강일",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "하남풍산",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2564",
      "stationName": "하남풍산",
      "exitNumbers": [
        "1",
        "5",
        "7"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "미사",
          "platformNumber": "1",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "하남풍산",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2565",
      "stationName": "하남시청",
      "exitNumbers": [
        "3",
        "5"
      ],
      "verificationMethod": "manual_direction_assignment",
      "directions": [
        {
          "toward": "하남풍산",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 6.1,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "하남검단산",
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 6.2,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    },
    {
      "stationCode": "2566",
      "stationName": "하남검단산",
      "exitNumbers": [
        "1",
        "4"
      ],
      "verificationMethod": "api_platform_linkage",
      "directions": [
        {
          "toward": "하남시청",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 6.4,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        },
        {
          "toward": "하남검단산",
          "platformNumber": "2",
          "recommendedDoors": [
            "5-3"
          ],
          "doorGaps": [
            {
              "door": "5-3",
              "gap": {
                "distanceCm": 5.8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null
        }
      ]
    }
  ]
} as const;
