// Generated by tools/validation/build-line2-guidance.mjs.
export const LINE_2_GUIDANCE = {
  "dataVersion": "line-2.audit-2026-09-18.manual-2026-09-30",
  "verifiedAt": "2026-09-30",
  "topologies": {
    "main": [
      "0201",
      "0243",
      "0242",
      "0241",
      "0240",
      "0239",
      "0238",
      "0237",
      "0236",
      "0235",
      "0234",
      "0233",
      "0232",
      "0231",
      "0230",
      "0229",
      "0228",
      "0227",
      "0226",
      "0225",
      "0224",
      "0223",
      "0222",
      "0221",
      "0220",
      "0219",
      "0218",
      "0217",
      "0216",
      "0215",
      "0214",
      "0213",
      "0212",
      "0211",
      "0210",
      "0209",
      "0208",
      "0207",
      "0206",
      "0205",
      "0204",
      "0203",
      "0202"
    ],
    "sinjeong": [
      "0234",
      "0247",
      "0248",
      "0249",
      "234-4"
    ],
    "seongsu": [
      "0211",
      "0244",
      "0245",
      "0250",
      "0246"
    ]
  },
  "stations": [
    {
      "stationCode": "0201",
      "stationName": "시청",
      "exitNumbers": [
        "9"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0201-live-1",
          "name": "승강기)엘리베이터-시청(2) 9번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "9번 출입구",
          "kind": "surface"
        },
        {
          "id": "0201-live-2",
          "name": "승강기)엘리베이터-시청(2) 섬식(외) 6-2 내부#1",
          "operatingSection": "B3-B2-B1",
          "location": "충정로 방면6-2, 을지로입구 방면5-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "을지로입구",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "5-3"
          ],
          "doorGaps": [
            {
              "door": "5-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "충정로",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "6-2"
          ],
          "doorGaps": [
            {
              "door": "6-2",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0243",
      "stationName": "충정로",
      "exitNumbers": [
        "5"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0243-live-1",
          "name": "승강기)엘리베이터-충정로 5번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "5번 출입구",
          "kind": "surface"
        },
        {
          "id": "0243-live-2",
          "name": "승강기)엘리베이터-충정로 섬식(외)2-1 내부#1",
          "operatingSection": "B3-B2",
          "location": "아현 방면2-1, 시청 방면9-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "아현",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "2-1"
          ],
          "doorGaps": [
            {
              "door": "2-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "시청",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "9-4"
          ],
          "doorGaps": [
            {
              "door": "9-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0242",
      "stationName": "아현",
      "exitNumbers": [
        "1",
        "3"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0242-live-1",
          "name": "승강기)엘리베이터-아현 1번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0242-live-2",
          "name": "승강기)엘리베이터-아현 3번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0242-live-3",
          "name": "승강기)엘리베이터-아현 내선 4-3 내부#2",
          "operatingSection": "B2-B1",
          "location": "충정로 방면4-3",
          "kind": "platform"
        },
        {
          "id": "0242-live-4",
          "name": "승강기)엘리베이터-아현 외선 7-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "이대 방면7-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "이대",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "7-2"
          ],
          "doorGaps": [
            {
              "door": "7-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "충정로",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 13,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0241",
      "stationName": "이대",
      "exitNumbers": [
        "2",
        "6"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0241-live-1",
          "name": "승강기)엘리베이터-이대 6번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0241-live-2",
          "name": "승강기)엘리베이터-이대 섬식(외)2-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "신촌 방면2-2, 아현 방면9-3",
          "kind": "platform"
        },
        {
          "id": "0241-live-3",
          "name": "승강기)엘리베이터-이대역 2번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "2번 출입구",
          "kind": "surface"
        }
      ],
      "directions": [
        {
          "toward": "신촌",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "2-2"
          ],
          "doorGaps": [
            {
              "door": "2-2",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "아현",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "9-3"
          ],
          "doorGaps": [
            {
              "door": "9-3",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0240",
      "stationName": "신촌",
      "exitNumbers": [
        "4",
        "6"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0240-live-1",
          "name": "승강기)엘리베이터-신촌 4번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0240-live-2",
          "name": "승강기)엘리베이터-신촌 6번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0240-live-3",
          "name": "승강기)엘리베이터-신촌 내선 4-4 내부#2",
          "operatingSection": "B2-B1",
          "location": "이대 방면4-4",
          "kind": "platform"
        },
        {
          "id": "0240-live-4",
          "name": "승강기)엘리베이터-신촌 외선 8-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "홍대입구 방면6-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "홍대입구",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "6-4"
          ],
          "doorGaps": [
            {
              "door": "6-4",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "이대",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 15.5,
                "level": "red",
                "label": "추천하지 않음"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0239",
      "stationName": "홍대입구",
      "exitNumbers": [
        "8"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0239-live-1",
          "name": "승강기)엘리베이터-홍대입구 8번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "8번 출입구",
          "kind": "surface"
        },
        {
          "id": "0239-live-2",
          "name": "승강기)엘리베이터-홍대입구 섬식(외)7-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "합정 방면7-2, 신촌 방면4-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "합정",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "7-2"
          ],
          "doorGaps": [
            {
              "door": "7-2",
              "gap": {
                "distanceCm": 5.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "신촌",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0238",
      "stationName": "합정",
      "exitNumbers": [
        "1",
        "4",
        "6",
        "9"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0238-live-1",
          "name": "승강기)엘리베이터-합정 1번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "1,2번 출입구 사이",
          "kind": "surface"
        },
        {
          "id": "0238-live-2",
          "name": "승강기)엘리베이터-합정 4번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "3,4번 출입구 사이",
          "kind": "surface"
        },
        {
          "id": "0238-live-3",
          "name": "승강기)엘리베이터-합정 내선 7-3 내부#2",
          "operatingSection": "B2-B1",
          "location": "홍대입구 방면7-3",
          "kind": "platform"
        },
        {
          "id": "0238-live-4",
          "name": "승강기)엘리베이터-합정 외선 4-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "당산 방면4-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "당산",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "4-2"
          ],
          "doorGaps": [
            {
              "door": "4-2",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "홍대입구",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "7-2"
          ],
          "doorGaps": [
            {
              "door": "7-2",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0237",
      "stationName": "당산",
      "exitNumbers": [
        "3",
        "4"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0237-live-1",
          "name": "승강기)엘리베이터-당산 3번 출구측 외부#2",
          "operatingSection": "1F-2F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0237-live-2",
          "name": "승강기)엘리베이터-당산 4번 출구측 외부#1",
          "operatingSection": "1F-2F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0237-live-3",
          "name": "승강기)엘리베이터-당산 내선 3-2 내부#2",
          "operatingSection": "2F-3F",
          "location": "합정 방면3-2",
          "kind": "platform"
        },
        {
          "id": "0237-live-4",
          "name": "승강기)엘리베이터-당산 외선 8-3 내부#1",
          "operatingSection": "2F-3F",
          "location": "영등포구청 방면8-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "영등포구청",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "합정",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0236",
      "stationName": "영등포구청",
      "exitNumbers": [
        "2",
        "5"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0236-live-1",
          "name": "승강기)엘리베이터-영등포구청 2번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "2번 출입구",
          "kind": "surface"
        },
        {
          "id": "0236-live-2",
          "name": "승강기)엘리베이터-영등포구청 내선 3-1 내부#2",
          "operatingSection": "B2-B1",
          "location": "당산 방면3-1",
          "kind": "platform"
        },
        {
          "id": "0236-live-3",
          "name": "승강기)엘리베이터-영등포구청 외선 8-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "문래 방면8-4",
          "kind": "platform"
        },
        {
          "id": "0236-live-4",
          "name": "승강기)엘리베이터-영등포구청(2) #5출입구 외부엘리베이터 2호기",
          "operatingSection": "B1-1F",
          "location": "5번 출입구",
          "kind": "surface"
        }
      ],
      "directions": [
        {
          "toward": "문래",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "당산",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0235",
      "stationName": "문래",
      "exitNumbers": [
        "1",
        "4",
        "5"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0235-live-1",
          "name": "승강기)엘리베이터-문래 1번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0235-live-2",
          "name": "승강기)엘리베이터-문래 5번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "5번 출입구",
          "kind": "surface"
        },
        {
          "id": "0235-live-3",
          "name": "승강기)엘리베이터-문래 내선 4-1 내부#2",
          "operatingSection": "B2-B1",
          "location": "영등포구청 방면4-1",
          "kind": "platform"
        },
        {
          "id": "0235-live-4",
          "name": "승강기)엘리베이터-문래 외선 7-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "신도림 방면7-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "신도림",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "4-1"
          ],
          "doorGaps": [
            {
              "door": "4-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "영등포구청",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "7-4"
          ],
          "doorGaps": [
            {
              "door": "7-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0234",
      "stationName": "신도림",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0234-live-1",
          "name": "승강기)엘리베이터-신도림 1번 출구측 외부#1",
          "operatingSection": "B1-2F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0234-live-2",
          "name": "승강기)엘리베이터-신도림 2번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0234-live-3",
          "name": "승강기)엘리베이터-신도림 섬식 3-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "대림 방면4-4, 문래 방면7-4",
          "kind": "platform"
        },
        {
          "id": "0234-live-4",
          "name": "승강기)엘리베이터-신도림 섬식 4-4 내부#2",
          "operatingSection": "B2-B1",
          "location": "대림 방면3-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "대림",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4",
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 6.5,
                "level": "green",
                "label": "안전"
              }
            },
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "문래",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "7-4"
          ],
          "doorGaps": [
            {
              "door": "7-4",
              "gap": {
                "distanceCm": 6.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "도림천",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "문래",
          "aliases": [],
          "service": "main",
          "platformNumber": "2",
          "recommendedDoors": [
            "7-1"
          ],
          "doorGaps": [
            {
              "door": "7-1",
              "gap": {
                "distanceCm": 6.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "대림",
          "aliases": [],
          "service": "main",
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 6.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "대림",
          "aliases": [],
          "service": "sinjeong",
          "platformNumber": null,
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "도림천",
          "aliases": [],
          "service": "sinjeong",
          "platformNumber": null,
          "recommendedDoors": [
            "1-3"
          ],
          "doorGaps": [
            {
              "door": "1-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0233",
      "stationName": "대림",
      "exitNumbers": [
        "3",
        "7"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0233-live-1",
          "name": "승강기)엘리베이터-대림 4번 출구측(육교) 외부#2",
          "operatingSection": "2F-3F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0233-live-2",
          "name": "승강기)엘리베이터-대림 7번 출구측(육교) 외부#1",
          "operatingSection": "2F-3F",
          "location": "7번 출입구",
          "kind": "surface"
        },
        {
          "id": "0233-live-3",
          "name": "승강기)엘리베이터-대림 내선 8-3 내부#2",
          "operatingSection": "1F-2F",
          "location": "신도림 방면 8-3",
          "kind": "platform"
        },
        {
          "id": "0233-live-4",
          "name": "승강기)엘리베이터-대림 외선 3-2 내부#1",
          "operatingSection": "1F-2F",
          "location": "구로디지털단지역 방면 3-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "구로디지털단지",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "신도림",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0247",
      "stationName": "도림천",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0247-live-1",
          "name": "승강기)엘리베이터-도림천 1~2번 출구측 외부#1",
          "operatingSection": "B3-B2-B1",
          "location": "양천구청 방면2-4",
          "kind": "platform"
        },
        {
          "id": "0247-live-2",
          "name": "승강기)엘리베이터-도림천 섬식(지) 4-4 내부#1",
          "operatingSection": "B3-B2",
          "location": "신도림 방면4-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "신도림",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "양천구청",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "2-4"
          ],
          "doorGaps": [
            {
              "door": "2-4",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "도림천",
          "aliases": [
            "양천구청"
          ],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "2-4"
          ],
          "doorGaps": [
            {
              "door": "2-4",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0248",
      "stationName": "양천구청",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0248-live-1",
          "name": "승강기)엘리베이터-양천구청 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0248-live-2",
          "name": "승강기)엘리베이터-양천구청 내선 3-3 내부#2",
          "operatingSection": "B2-B1",
          "location": "도림천 방면3-3",
          "kind": "platform"
        },
        {
          "id": "0248-live-3",
          "name": "승강기)엘리베이터-양천구청 외선 4-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "신정네거리 방면4-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "도림천",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "신정네거리",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-1"
          ],
          "doorGaps": [
            {
              "door": "4-1",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0232",
      "stationName": "구로디지털단지",
      "exitNumbers": [
        "1",
        "2"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0232-live-1",
          "name": "승강기)엘리베이터-구로디지털단지 #2,3출입구 외부엘리베이터 2호기",
          "operatingSection": "1F-2F",
          "location": "2,3번 출입구 사이",
          "kind": "surface"
        },
        {
          "id": "0232-live-2",
          "name": "승강기)엘리베이터-구로디지털단지 6번 출구측 외부#1",
          "operatingSection": "2F-3F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0232-live-3",
          "name": "승강기)엘리베이터-구로디지털단지 내선 7-4 내부#2",
          "operatingSection": "2F-3F",
          "location": "대림 방면7-4",
          "kind": "platform"
        },
        {
          "id": "0232-live-4",
          "name": "승강기)엘리베이터-구로디지털단지 외선 3-4 내부#1",
          "operatingSection": "1F-2F",
          "location": "신대방 방면3-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "신대방",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 13.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "대림",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "7-4"
          ],
          "doorGaps": [
            {
              "door": "7-4",
              "gap": {
                "distanceCm": 6.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0231",
      "stationName": "신대방",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0231-live-1",
          "name": "승강기)엘리베이터-신대방 1번 출구측 외부#1",
          "operatingSection": "1F-2F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0231-live-2",
          "name": "승강기)엘리베이터-신대방 내선 8-1 내부#2",
          "operatingSection": "2F-3F",
          "location": "구로디지털단지 방면8-1",
          "kind": "platform"
        },
        {
          "id": "0231-live-3",
          "name": "승강기)엘리베이터-신대방 외선 3-4 내부#1",
          "operatingSection": "2F-3F",
          "location": "신림방면 3-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "신림",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "구로디지털단지",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "8-1"
          ],
          "doorGaps": [
            {
              "door": "8-1",
              "gap": {
                "distanceCm": 11.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0249",
      "stationName": "신정네거리",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0249-live-1",
          "name": "승강기)엘리베이터-신정네거리 2,3번출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "2번 출입구",
          "kind": "surface"
        },
        {
          "id": "0249-live-2",
          "name": "승강기)엘리베이터-신정네거리 내선 3-4 내부#2",
          "operatingSection": "B3-B2",
          "location": "양천구청 방면3-4",
          "kind": "platform"
        },
        {
          "id": "0249-live-3",
          "name": "승강기)엘리베이터-신정네거리 외선 4-1 내부#1",
          "operatingSection": "B3-B2",
          "location": "까치산 방면4-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "양천구청",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "까치산",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-1"
          ],
          "doorGaps": [
            {
              "door": "4-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0230",
      "stationName": "신림",
      "exitNumbers": [
        "1",
        "5"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0230-live-1",
          "name": "승강기)엘리베이터-신림 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0230-live-2",
          "name": "승강기)엘리베이터-신림 5번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "5번 출입구",
          "kind": "surface"
        },
        {
          "id": "0230-live-3",
          "name": "승강기)엘리베이터-신림 섬식(외) 4-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "신대방 방면7-1, 봉천 방면4-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "봉천",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 10.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "신대방",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "7-1"
          ],
          "doorGaps": [
            {
              "door": "7-1",
              "gap": {
                "distanceCm": 9.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "234-4",
      "stationName": "까치산",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [],
      "directions": [
        {
          "toward": "신정네거리",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "0229",
      "stationName": "봉천",
      "exitNumbers": [
        "4"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0229-live-1",
          "name": "승강기)엘리베이터-봉천 4번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0229-live-2",
          "name": "승강기)엘리베이터-봉천 섬식(외)6-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "서울대입구 방면6-3, 신림 방면5-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "서울대입구",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "6-3"
          ],
          "doorGaps": [
            {
              "door": "6-3",
              "gap": {
                "distanceCm": 6.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "신림",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "5-1"
          ],
          "doorGaps": [
            {
              "door": "5-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0228",
      "stationName": "서울대입구",
      "exitNumbers": [
        "2",
        "6"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0228-live-1",
          "name": "승강기)엘리베이터-서울대입구 2번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "2번 출입구",
          "kind": "surface"
        },
        {
          "id": "0228-live-2",
          "name": "승강기)엘리베이터-서울대입구 6번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0228-live-3",
          "name": "승강기)엘리베이터-서울대입구 섬식(외)6-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "봉천 방면5-2, 낙성대 방면6-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "낙성대",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "6-3"
          ],
          "doorGaps": [
            {
              "door": "6-3",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "봉천",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "5-2"
          ],
          "doorGaps": [
            {
              "door": "5-2",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0227",
      "stationName": "낙성대",
      "exitNumbers": [
        "6"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0227-live-1",
          "name": "승강기)엘리베이터-낙성대 6번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0227-live-2",
          "name": "승강기)엘리베이터-낙성대 내선 3-3 내부#2",
          "operatingSection": "B2-B1",
          "location": "서울대입구 방면3-3",
          "kind": "platform"
        },
        {
          "id": "0227-live-3",
          "name": "승강기)엘리베이터-낙성대 외선 8-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "사당 방면8-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "사당",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "8-2"
          ],
          "doorGaps": [
            {
              "door": "8-2",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "서울대입구",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0226",
      "stationName": "사당",
      "exitNumbers": [
        "6",
        "14"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0226-live-1",
          "name": "승강기)엘리베이터-사당(2) 14번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "14번 출입구",
          "kind": "surface"
        },
        {
          "id": "0226-live-2",
          "name": "승강기)엘리베이터-사당(2) 6번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0226-live-3",
          "name": "승강기)엘리베이터-사당(2) 섬식(외)4-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "방배 방면4-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "방배",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "낙성대",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "0225",
      "stationName": "방배",
      "exitNumbers": [
        "3"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0225-live-1",
          "name": "승강기)엘리베이터-방배 3번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0225-live-2",
          "name": "승강기)엘리베이터-방배 내선 3-1 내부#2",
          "operatingSection": "B2-B1",
          "location": "사당 방면3-1",
          "kind": "platform"
        },
        {
          "id": "0225-live-3",
          "name": "승강기)엘리베이터-방배 외선 8-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "서초 방면8-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "서초",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 6,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "사당",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0224",
      "stationName": "서초",
      "exitNumbers": [
        "1",
        "3",
        "4"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0224-live-1",
          "name": "승강기)엘리베이터-서초  4번출구 외부#2",
          "operatingSection": "B1-1F",
          "location": "3,4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0224-live-2",
          "name": "승강기)엘리베이터-서초 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0224-live-3",
          "name": "승강기)엘리베이터-서초 내선 9-1 내부#2",
          "operatingSection": "B2-B1",
          "location": "방배 방면9-1",
          "kind": "platform"
        },
        {
          "id": "0224-live-4",
          "name": "승강기)엘리베이터-서초 외선 2-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "교대 방면2-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "교대",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "2-4"
          ],
          "doorGaps": [
            {
              "door": "2-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "방배",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "9-1"
          ],
          "doorGaps": [
            {
              "door": "9-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0223",
      "stationName": "교대",
      "exitNumbers": [
        "5",
        "13"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0223-live-1",
          "name": "승강기)엘리베이터-교대(2) 5번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "5번 출입구",
          "kind": "surface"
        },
        {
          "id": "0223-live-2",
          "name": "승강기)엘리베이터-교대(2) 내선 3-1 내부#2",
          "operatingSection": "B2-B1",
          "location": "서초 방면3-1",
          "kind": "platform"
        },
        {
          "id": "0223-live-3",
          "name": "승강기)엘리베이터-교대(2) 외선 8-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "강남 방면8-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "강남",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "서초",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0222",
      "stationName": "강남",
      "exitNumbers": [
        "1",
        "8",
        "10"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0222-live-1",
          "name": "승강기)엘리베이터-강남 10번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "10번 출입구",
          "kind": "surface"
        },
        {
          "id": "0222-live-2",
          "name": "승강기)엘리베이터-강남 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0222-live-3",
          "name": "승강기)엘리베이터-강남 내선 3-4 내부#2",
          "operatingSection": "B2-B1",
          "location": "교대 방면3-4",
          "kind": "platform"
        },
        {
          "id": "0222-live-4",
          "name": "승강기)엘리베이터-강남 외선 8-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "역삼 방면8-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "역삼",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "8-1"
          ],
          "doorGaps": [
            {
              "door": "8-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "교대",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0221",
      "stationName": "역삼",
      "exitNumbers": [
        "3",
        "4"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0221-live-1",
          "name": "승강기)엘리베이터-역삼 3번 출구측 외부#1",
          "operatingSection": "B2-1F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0221-live-2",
          "name": "승강기)엘리베이터-역삼 4번 출구측 외부#2",
          "operatingSection": "B2-1F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0221-live-3",
          "name": "승강기)엘리베이터-역삼 내선 4-1 내부#2",
          "operatingSection": "B3-B2",
          "location": "강남 방면4-1",
          "kind": "platform"
        },
        {
          "id": "0221-live-4",
          "name": "승강기)엘리베이터-역삼 외선 7-3 내부#1",
          "operatingSection": "B3-B2",
          "location": "선릉 방면7-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "선릉",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "7-3"
          ],
          "doorGaps": [
            {
              "door": "7-3",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "강남",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-1"
          ],
          "doorGaps": [
            {
              "door": "4-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0220",
      "stationName": "선릉",
      "exitNumbers": [
        "1",
        "5",
        "10"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0220-live-1",
          "name": "승강기)엘리베이터-선릉 10번 출구측 외부#3",
          "operatingSection": "B1-1F",
          "location": "10번 출입구",
          "kind": "surface"
        },
        {
          "id": "0220-live-2",
          "name": "승강기)엘리베이터-선릉 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0220-live-3",
          "name": "승강기)엘리베이터-선릉 5번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "5번 출입구",
          "kind": "surface"
        }
      ],
      "directions": [
        {
          "toward": "삼성",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "역삼",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        }
      ]
    },
    {
      "stationCode": "0219",
      "stationName": "삼성",
      "exitNumbers": [
        "1",
        "4",
        "6"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0219-live-1",
          "name": "승강기)엘리베이터-삼성 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0219-live-2",
          "name": "승강기)엘리베이터-삼성 4번 출구측 외부#4",
          "operatingSection": "B1-1F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0219-live-3",
          "name": "승강기)엘리베이터-삼성 6번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0219-live-4",
          "name": "승강기)엘리베이터-삼성 8번 출구측 외부#3",
          "operatingSection": "B1-1F",
          "location": "8번 출입구",
          "kind": "surface"
        },
        {
          "id": "0219-live-5",
          "name": "승강기)엘리베이터-삼성 섬식(외) 3-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "종합운동장 방면3-1, 선릉 방면8-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "종합운동장",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": {
                "distanceCm": 5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "선릉",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0218",
      "stationName": "종합운동장",
      "exitNumbers": [
        "6"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0218-live-1",
          "name": "승강기)엘리베이터-종합운동장 6번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0218-live-2",
          "name": "승강기)엘리베이터-종합운동장 내선 8-4 내부#2",
          "operatingSection": "B2-B1",
          "location": "삼성 방면8-4",
          "kind": "platform"
        },
        {
          "id": "0218-live-3",
          "name": "승강기)엘리베이터-종합운동장 외선 2-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "잠실새내 방면2-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "잠실새내",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "2-4"
          ],
          "doorGaps": [
            {
              "door": "2-4",
              "gap": {
                "distanceCm": 11,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "삼성",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 10.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0217",
      "stationName": "잠실새내",
      "exitNumbers": [
        "2",
        "7"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0217-live-1",
          "name": "승강기)엘리베이터-잠실새내 2번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "2번 출입구",
          "kind": "surface"
        },
        {
          "id": "0217-live-2",
          "name": "승강기)엘리베이터-잠실새내 7번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "7번 출입구",
          "kind": "surface"
        },
        {
          "id": "0217-live-3",
          "name": "승강기)엘리베이터-잠실새내 내선 4-1 내부#2",
          "operatingSection": "B2-B1",
          "location": "종합운동장 방면4-1",
          "kind": "platform"
        },
        {
          "id": "0217-live-4",
          "name": "승강기)엘리베이터-잠실새내 외선 7-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "잠실방면7-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "잠실",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "7-3"
          ],
          "doorGaps": [
            {
              "door": "7-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "종합운동장",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "4-1"
          ],
          "doorGaps": [
            {
              "door": "4-1",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0216",
      "stationName": "잠실",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0216-live-1",
          "name": "승강기)엘리베이터-잠실 1,2번출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0216-live-2",
          "name": "승강기)엘리베이터-잠실 6번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0216-live-3",
          "name": "승강기)엘리베이터-잠실 내선 6-3 내부#2",
          "operatingSection": "B2-B1",
          "location": "잠실새내 방면6-3",
          "kind": "platform"
        },
        {
          "id": "0216-live-4",
          "name": "승강기)엘리베이터-잠실 외선 5-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "잠실나루 방면5-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "잠실나루",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "5-2"
          ],
          "doorGaps": [
            {
              "door": "5-2",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "잠실새내",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "6-3"
          ],
          "doorGaps": [
            {
              "door": "6-3",
              "gap": {
                "distanceCm": 7,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0215",
      "stationName": "잠실나루",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0215-live-1",
          "name": "승강기)엘리베이터-잠실나루 내선 8-1 내부#2",
          "operatingSection": "1F-2F",
          "location": "잠실 방면8-1",
          "kind": "platform"
        },
        {
          "id": "0215-live-2",
          "name": "승강기)엘리베이터-잠실나루 외선 3-4 내부#1",
          "operatingSection": "1F-2F",
          "location": "강변 방면3-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "강변",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "잠실",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "8-1"
          ],
          "doorGaps": [
            {
              "door": "8-1",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0214",
      "stationName": "강변",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0214-live-1",
          "name": "승강기)엘리베이터-강변 내선 7-3 내부#2",
          "operatingSection": "1F-2F",
          "location": "잠실나루 방면7-3",
          "kind": "platform"
        },
        {
          "id": "0214-live-2",
          "name": "승강기)엘리베이터-강변 외선 4-2 내부#1",
          "operatingSection": "1F-2F",
          "location": "구의 방면4-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "구의",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "4-2"
          ],
          "doorGaps": [
            {
              "door": "4-2",
              "gap": {
                "distanceCm": 6.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "잠실나루",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "7-3"
          ],
          "doorGaps": [
            {
              "door": "7-3",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0213",
      "stationName": "구의",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0213-live-1",
          "name": "승강기)엘리베이터-구의 2번 출구측 외부#1",
          "operatingSection": "1F-2F-3F",
          "location": "2번 출입구",
          "kind": "surface"
        },
        {
          "id": "0213-live-2",
          "name": "승강기)엘리베이터-구의 섬식(외)4-3 내부#1",
          "operatingSection": "2F-3F",
          "location": "강변 방면4-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "건대입구",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "강변",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0212",
      "stationName": "건대입구",
      "exitNumbers": [
        "1",
        "6"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0212-live-1",
          "name": "승강기)엘리베이터-건대입구 7-3~6번 출구측 외부#1",
          "operatingSection": "1F-2F-3F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0212-live-2",
          "name": "승강기)엘리베이터-건대입구 섬식(외)5-4 내부#1",
          "operatingSection": "2F-3F",
          "location": "성수 방면5-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "구의",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "7-3"
          ],
          "doorGaps": [
            {
              "door": "7-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "성수",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0211",
      "stationName": "성수",
      "exitNumbers": [
        "1",
        "4"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0211-live-1",
          "name": "승강기)엘리베이터-성수 1번 출구측 외부#1",
          "operatingSection": "1F-2F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0211-live-2",
          "name": "승강기)엘리베이터-성수 4번 출구측 외부#2",
          "operatingSection": "1F-2F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0211-live-3",
          "name": "승강기)엘리베이터-성수 내선 4-4 내부#2",
          "operatingSection": "2F-3F",
          "location": "건대입구 방면4-4",
          "kind": "platform"
        },
        {
          "id": "0211-live-4",
          "name": "승강기)엘리베이터-성수 외선 7-1 내부#1",
          "operatingSection": "2F-3F",
          "location": "뚝섬 방면7-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "뚝섬",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "7-1"
          ],
          "doorGaps": [
            {
              "door": "7-1",
              "gap": {
                "distanceCm": 5.2,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "건대입구",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 5.6,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0210",
      "stationName": "뚝섬",
      "exitNumbers": [
        "3",
        "6"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0210-live-1",
          "name": "승강기)엘리베이터-뚝섬 3번 출구측 외부#1",
          "operatingSection": "1F-2F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0210-live-2",
          "name": "승강기)엘리베이터-뚝섬 6번 출구측 외부#2",
          "operatingSection": "1F-2F",
          "location": "6번 출입구",
          "kind": "surface"
        },
        {
          "id": "0210-live-3",
          "name": "승강기)엘리베이터-뚝섬 내선 7-1 내부#2",
          "operatingSection": "2F-3F",
          "location": "성수 방면7-1",
          "kind": "platform"
        },
        {
          "id": "0210-live-4",
          "name": "승강기)엘리베이터-뚝섬 외선 7-1 내부#1",
          "operatingSection": "2F-3F",
          "location": "한양대 방면7-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "한양대",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "7-1"
          ],
          "doorGaps": [
            {
              "door": "7-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "성수",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "7-1"
          ],
          "doorGaps": [
            {
              "door": "7-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0244",
      "stationName": "용답",
      "exitNumbers": [],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0244-live-1",
          "name": "승강기)엘리베이터-성수방면 3-3 내부2호기",
          "operatingSection": "2F-3F",
          "location": "성수방면3-3",
          "kind": "platform"
        },
        {
          "id": "0244-live-2",
          "name": "승강기)엘리베이터-신답방면 2-2 내부1호기",
          "operatingSection": "2F-3F",
          "location": "신답방면2-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "성수",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "신답",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "2-2"
          ],
          "doorGaps": [
            {
              "door": "2-2",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0209",
      "stationName": "한양대",
      "exitNumbers": [
        "2",
        "4"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0209-live-1",
          "name": "승강기)엘리베이터-한양대 4번 출구(육교) 외부#1",
          "operatingSection": "1F-2F",
          "location": "4번 출입구(육교) 측",
          "kind": "surface"
        },
        {
          "id": "0209-live-2",
          "name": "승강기)엘리베이터-한양대 섬식(외) 3-3 내부#1",
          "operatingSection": "1F-2F",
          "location": "왕십리 방면3-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "왕십리",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-3"
          ],
          "doorGaps": [
            {
              "door": "3-3",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "뚝섬",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": {
                "distanceCm": 8.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0245",
      "stationName": "신답",
      "exitNumbers": [],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0245-live-1",
          "name": "승강기)엘리베이터-신답 내선 3-2 내부#2",
          "operatingSection": "1F-2F",
          "location": "용답 방면3-2",
          "kind": "platform"
        },
        {
          "id": "0245-live-2",
          "name": "승강기)엘리베이터-신답 외선 2-4 내부#1",
          "operatingSection": "1F-2F",
          "location": "용두 방면2-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "용답",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "용두",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "2-4"
          ],
          "doorGaps": [
            {
              "door": "2-4",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0250",
      "stationName": "용두",
      "exitNumbers": [
        "3",
        "4"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0250-live-1",
          "name": "승강기)엘리베이터-용두 3번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "3번 출입구",
          "kind": "surface"
        },
        {
          "id": "0250-live-2",
          "name": "승강기)엘리베이터-용두 4번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "4번 출입구",
          "kind": "surface"
        },
        {
          "id": "0250-live-3",
          "name": "승강기)엘리베이터-용두 내선 4-3 내부#2",
          "operatingSection": "B2-B1",
          "location": "신답 방면1-1",
          "kind": "platform"
        },
        {
          "id": "0250-live-4",
          "name": "승강기)엘리베이터-용두 외선 1-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "신설동 방면4-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "신답",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "1-1"
          ],
          "doorGaps": [
            {
              "door": "1-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "신설동",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-3"
          ],
          "doorGaps": [
            {
              "door": "4-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0208",
      "stationName": "왕십리",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0208-live-1",
          "name": "승강기)엘리베이터-왕십리 내선 3-4 내부#2",
          "operatingSection": "B3-B2",
          "location": "한양대 방면3-4",
          "kind": "platform"
        },
        {
          "id": "0208-live-2",
          "name": "승강기)엘리베이터-왕십리 외선 3-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "상왕십리 방면3-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "상왕십리",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "한양대",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 4,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0246",
      "stationName": "신설동",
      "exitNumbers": [
        "9"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0246-live-1",
          "name": "승강기)엘리베이터-신설동(2) 9번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "9번 출입구",
          "kind": "surface"
        },
        {
          "id": "0246-live-2",
          "name": "승강기)엘리베이터-신설동(2) 섬식(외) 4-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "신설동 방면4-4",
          "kind": "platform"
        },
        {
          "id": "0246-live-3",
          "name": "엘리베이터-신설동(2) 외부 E/L 외부2",
          "operatingSection": "B2-1F",
          "location": "9번 출입구",
          "kind": "surface"
        }
      ],
      "directions": [
        {
          "toward": "용두",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [],
          "doorGaps": [],
          "accessibilityVerified": false,
          "warning": "방향별 승강기 인접 차량·문 미확인",
          "source": "unverified"
        },
        {
          "toward": "신설동",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-4"
          ],
          "doorGaps": [
            {
              "door": "4-4",
              "gap": {
                "distanceCm": 8,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0207",
      "stationName": "상왕십리",
      "exitNumbers": [
        "1-1"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0207-live-1",
          "name": "승강기)엘리베이터-상왕십리 내선 3-4 내부#2",
          "operatingSection": "B2-B1",
          "location": "왕십리 방면3-4",
          "kind": "platform"
        },
        {
          "id": "0207-live-2",
          "name": "승강기)엘리베이터-상왕십리 외부#1",
          "operatingSection": "B1-1F",
          "location": "1-1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0207-live-3",
          "name": "승강기)엘리베이터-상왕십리 외선 8-1 내부#1",
          "operatingSection": "B2-B1",
          "location": "신당 방면8-1",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "신당",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "7-4"
          ],
          "doorGaps": [
            {
              "door": "7-4",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "왕십리",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "4-1"
          ],
          "doorGaps": [
            {
              "door": "4-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0206",
      "stationName": "신당",
      "exitNumbers": [
        "2"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0206-live-1",
          "name": "승강기)엘리베이터-신당 2번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "2번 출입구",
          "kind": "surface"
        },
        {
          "id": "0206-live-2",
          "name": "승강기)엘리베이터-신당 내선 7-4 내부#2",
          "operatingSection": "B2-B1",
          "location": "상왕십리 방면7-4",
          "kind": "platform"
        },
        {
          "id": "0206-live-3",
          "name": "승강기)엘리베이터-신당 외선 3-4 내부#1",
          "operatingSection": "B2-B1",
          "location": "동대문역사문화공원 방면3-4",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "동대문역사문화공원",
          "aliases": [],
          "service": null,
          "platformNumber": "1",
          "recommendedDoors": [
            "3-4"
          ],
          "doorGaps": [
            {
              "door": "3-4",
              "gap": {
                "distanceCm": 10,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "상왕십리",
          "aliases": [],
          "service": null,
          "platformNumber": "2",
          "recommendedDoors": [
            "7-4"
          ],
          "doorGaps": [
            {
              "door": "7-4",
              "gap": {
                "distanceCm": 7.5,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0205",
      "stationName": "동대문역사문화공원",
      "exitNumbers": [
        "1"
      ],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0205-live-1",
          "name": "승강기)엘리베이터-동역사(2) 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0205-live-2",
          "name": "승강기)엘리베이터-동역사(2) 내선 3-2 내부#2",
          "operatingSection": "B2-B1",
          "location": "신당 방면3-2",
          "kind": "platform"
        },
        {
          "id": "0205-live-3",
          "name": "승강기)엘리베이터-동역사(2) 외선 8-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "을지로4가 방면8-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "을지로4가",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "신당",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0204",
      "stationName": "을지로4가",
      "exitNumbers": [
        "8",
        "10"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0204-live-1",
          "name": "승강기)엘리베이터-을지로4가 8번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "8번 출입구",
          "kind": "surface"
        },
        {
          "id": "0204-live-2",
          "name": "승강기)엘리베이터-을지로4가 내선 8-3 내부#2",
          "operatingSection": "B2-B1",
          "location": "동대문역사문화공원 방면8-3",
          "kind": "platform"
        },
        {
          "id": "0204-live-3",
          "name": "승강기)엘리베이터-을지로4가 외선 3-2 내부#1",
          "operatingSection": "B2-B1",
          "location": "을지로3가 방면3-2",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "을지로3가",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-1"
          ],
          "doorGaps": [
            {
              "door": "3-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "동대문역사문화공원",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-4"
          ],
          "doorGaps": [
            {
              "door": "8-4",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    },
    {
      "stationCode": "0203",
      "stationName": "을지로3가",
      "exitNumbers": [],
      "verificationMethod": "SeoulMetroFaciInfo",
      "liveElevators": [
        {
          "id": "0203-live-1",
          "name": "승강기)엘리베이터-을지로3가(2) 내선 3-2 내부#2",
          "operatingSection": "B2-B1",
          "location": "을지로4가 방면3-2",
          "kind": "platform"
        },
        {
          "id": "0203-live-2",
          "name": "승강기)엘리베이터-을지로3가(2) 외선 8-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "을지로입구 방면8-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "을지로입구",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "8-3"
          ],
          "doorGaps": [
            {
              "door": "8-3",
              "gap": {
                "distanceCm": 10.5,
                "level": "yellow",
                "label": "유의"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        },
        {
          "toward": "을지로4가",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "3-2"
          ],
          "doorGaps": [
            {
              "door": "3-2",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "SeoulMetroFaciInfo"
        }
      ]
    },
    {
      "stationCode": "0202",
      "stationName": "을지로입구",
      "exitNumbers": [
        "1",
        "5"
      ],
      "verificationMethod": "manual_verification",
      "liveElevators": [
        {
          "id": "0202-live-1",
          "name": "승강기)엘리베이터-을지로입구 1번 출구측 외부#1",
          "operatingSection": "B1-1F",
          "location": "1번 출입구",
          "kind": "surface"
        },
        {
          "id": "0202-live-2",
          "name": "승강기)엘리베이터-을지로입구 5번 출구측 외부#2",
          "operatingSection": "B1-1F",
          "location": "5,6번 출입구 사이",
          "kind": "surface"
        },
        {
          "id": "0202-live-3",
          "name": "승강기)엘리베이터-을지로입구 내선 6-2 내부#2",
          "operatingSection": "B2-B1",
          "location": "을지로3가 방면6-2",
          "kind": "platform"
        },
        {
          "id": "0202-live-4",
          "name": "승강기)엘리베이터-을지로입구 외선 5-3 내부#1",
          "operatingSection": "B2-B1",
          "location": "시청 방면5-3",
          "kind": "platform"
        }
      ],
      "directions": [
        {
          "toward": "시청",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "5-4"
          ],
          "doorGaps": [
            {
              "door": "5-4",
              "gap": {
                "distanceCm": 9,
                "level": "green",
                "label": "안전"
              }
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        },
        {
          "toward": "을지로3가",
          "aliases": [],
          "service": null,
          "platformNumber": null,
          "recommendedDoors": [
            "6-1"
          ],
          "doorGaps": [
            {
              "door": "6-1",
              "gap": null
            }
          ],
          "accessibilityVerified": true,
          "warning": null,
          "source": "manual_verification"
        }
      ]
    }
  ]
} as const;
